-- DBlossom complete Supabase setup. Run this file once in the Supabase SQL Editor.
-- It concatenates migrations in dependency order.

-- ===== supabase/migrations/0001_school_management.sql =====
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('admin', 'teacher', 'student', 'parent')),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  grade_level text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  academic_year text not null
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  student_number text not null unique,
  date_of_birth date,
  guardian_name text,
  guardian_contact text
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  class_id bigint not null references public.classes(id) on delete cascade
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  date date not null,
  status text not null check (status in ('present', 'absent', 'late', 'excused')),
  recorded_by uuid not null references public.profiles(id) on delete restrict
);

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  term text not null,
  score numeric not null check (score >= 0),
  max_score numeric not null default 100 check (max_score > 0),
  recorded_by uuid not null references public.profiles(id) on delete restrict
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  posted_by uuid not null references public.profiles(id) on delete restrict,
  class_id bigint references public.classes(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists classes_teacher_id_idx on public.classes(teacher_id);
create index if not exists students_profile_id_idx on public.students(profile_id);
create index if not exists students_class_id_idx on public.students(class_id);
create index if not exists attendance_student_date_idx on public.attendance(student_id, date);
create index if not exists grades_student_term_idx on public.grades(student_id, term);
create index if not exists announcements_class_id_idx on public.announcements(class_id);

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'admin', false);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    coalesce(new.raw_user_meta_data ->> 'role', 'student'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.subjects enable row level security;
alter table public.attendance enable row level security;
alter table public.grades enable row level security;
alter table public.announcements enable row level security;

drop policy if exists profiles_admin_all on public.profiles;
create policy profiles_admin_all on public.profiles for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select using (id = auth.uid());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists classes_admin_all on public.classes;
create policy classes_admin_all on public.classes for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists classes_teacher_read on public.classes;
create policy classes_teacher_read on public.classes for select using (teacher_id = auth.uid());
drop policy if exists classes_teacher_update on public.classes;
create policy classes_teacher_update on public.classes for update using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());

drop policy if exists students_admin_all on public.students;
create policy students_admin_all on public.students for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists students_self_read on public.students;
create policy students_self_read on public.students for select using (profile_id = auth.uid());
drop policy if exists students_teacher_read on public.students;
create policy students_teacher_read on public.students for select using (exists (select 1 from public.classes c where c.id = students.class_id and c.teacher_id = auth.uid()));

drop policy if exists subjects_admin_all on public.subjects;
create policy subjects_admin_all on public.subjects for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists subjects_teacher_read on public.subjects;
create policy subjects_teacher_read on public.subjects for select using (exists (select 1 from public.classes c where c.id = subjects.class_id and c.teacher_id = auth.uid()));

drop policy if exists attendance_admin_all on public.attendance;
create policy attendance_admin_all on public.attendance for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists attendance_teacher_class on public.attendance;
create policy attendance_teacher_class on public.attendance for all using (exists (select 1 from public.students s join public.classes c on c.id = s.class_id where s.id = attendance.student_id and c.teacher_id = auth.uid())) with check (recorded_by = auth.uid());
drop policy if exists attendance_student_read on public.attendance;
create policy attendance_student_read on public.attendance for select using (exists (select 1 from public.students s where s.id = attendance.student_id and s.profile_id = auth.uid()));

drop policy if exists grades_admin_all on public.grades;
create policy grades_admin_all on public.grades for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists grades_teacher_class on public.grades;
create policy grades_teacher_class on public.grades for all using (exists (select 1 from public.students s join public.classes c on c.id = s.class_id join public.subjects sub on sub.id = grades.subject_id and sub.class_id = c.id where s.id = grades.student_id and c.teacher_id = auth.uid())) with check (recorded_by = auth.uid());
drop policy if exists grades_student_read on public.grades;
create policy grades_student_read on public.grades for select using (exists (select 1 from public.students s where s.id = grades.student_id and s.profile_id = auth.uid()));

drop policy if exists announcements_admin_all on public.announcements;
create policy announcements_admin_all on public.announcements for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists announcements_teacher_manage on public.announcements;
create policy announcements_teacher_manage on public.announcements for all using (posted_by = auth.uid()) with check (posted_by = auth.uid());
drop policy if exists announcements_authenticated_read on public.announcements;
create policy announcements_authenticated_read on public.announcements for select using (auth.uid() is not null and (class_id is null or exists (select 1 from public.students s where s.class_id = announcements.class_id and s.profile_id = auth.uid())));

-- ===== supabase/migrations/0002_legacy_workflows.sql =====
alter table public.profiles
  add column if not exists staff_id text unique,
  add column if not exists assigned_class text,
  add column if not exists subject text,
  add column if not exists status text not null default 'Active';

alter table public.students
  add column if not exists gender text,
  add column if not exists parent_name text,
  add column if not exists parent_phone text,
  add column if not exists parent_email text,
  add column if not exists boarding_status text not null default 'Day',
  add column if not exists status text not null default 'Active';

create table if not exists public.portal_credentials (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  login_identifier text not null unique,
  login_email text not null unique,
  credential_type text not null check (credential_type in ('student', 'teacher', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  term text not null,
  session text not null,
  subjects jsonb not null default '[]'::jsonb,
  total_score numeric not null default 0,
  average numeric not null default 0,
  overall_percentage numeric not null default 0,
  teacher_comment text,
  principal_comment text,
  recorded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_name text not null,
  admission_number text,
  amount numeric not null default 0,
  payment_method text,
  reference text,
  proof_url text,
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed', 'Rejected')),
  submitted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  event_date date not null,
  image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  title text not null,
  alt_text text,
  image_url text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'New' check (status in ('New', 'In Progress', 'Resolved')),
  created_at timestamptz not null default now()
);

create index if not exists results_student_term_session_idx on public.results(student_id, term, session);
create index if not exists payments_status_idx on public.payments(status);
create index if not exists events_date_idx on public.events(event_date);
create index if not exists complaints_status_idx on public.complaints(status);

create or replace function public.resolve_portal_login(identifier text, portal_type text)
returns table (login_email text)
language sql
stable
security definer
set search_path = public
as $$
  select pc.login_email
  from public.portal_credentials pc
  where pc.login_identifier = identifier
    and pc.credential_type = portal_type
  limit 1;
$$;

grant execute on function public.resolve_portal_login(text, text) to anon, authenticated;

alter table public.portal_credentials enable row level security;
alter table public.results enable row level security;
alter table public.payments enable row level security;
alter table public.events enable row level security;
alter table public.gallery_images enable row level security;
alter table public.complaints enable row level security;

drop policy if exists portal_credentials_admin_all on public.portal_credentials;
create policy portal_credentials_admin_all on public.portal_credentials for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists results_admin_all on public.results;
create policy results_admin_all on public.results for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists results_teacher_assigned_class on public.results;
create policy results_teacher_assigned_class on public.results for all using (
  exists (
    select 1 from public.students s join public.classes c on c.id = s.class_id
    join public.profiles p on p.id = auth.uid()
    where s.id = results.student_id and c.teacher_id = auth.uid() and p.role = 'teacher'
  )
) with check (recorded_by = auth.uid());
drop policy if exists results_student_read on public.results;
create policy results_student_read on public.results for select using (
  exists (select 1 from public.students s where s.id = results.student_id and s.profile_id = auth.uid())
);

drop policy if exists payments_admin_all on public.payments;
create policy payments_admin_all on public.payments for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists payments_public_insert on public.payments;
create policy payments_public_insert on public.payments for insert with check (auth.uid() is null or submitted_by = auth.uid());

drop policy if exists events_public_read on public.events;
create policy events_public_read on public.events for select using (true);
drop policy if exists events_admin_write on public.events;
create policy events_admin_write on public.events for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists gallery_public_read on public.gallery_images;
create policy gallery_public_read on public.gallery_images for select using (true);
drop policy if exists gallery_admin_write on public.gallery_images;
create policy gallery_admin_write on public.gallery_images for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists complaints_public_insert on public.complaints;
create policy complaints_public_insert on public.complaints for insert with check (true);
drop policy if exists complaints_admin_all on public.complaints;
create policy complaints_admin_all on public.complaints for all using (public.is_admin()) with check (public.is_admin());

-- ===== supabase/migrations/0003_role_hardening.sql =====
create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'teacher', false);
$$;

create or replace function public.is_student()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'student', false);
$$;

drop policy if exists attendance_teacher_class on public.attendance;
create policy attendance_teacher_class on public.attendance for all
using (
  public.is_teacher() and exists (
    select 1 from public.students s
    join public.classes c on c.id = s.class_id
    where s.id = attendance.student_id and c.teacher_id = auth.uid()
  )
)
with check (public.is_teacher() and recorded_by = auth.uid());

drop policy if exists grades_teacher_class on public.grades;
create policy grades_teacher_class on public.grades for all
using (
  public.is_teacher() and exists (
    select 1 from public.students s
    join public.classes c on c.id = s.class_id
    join public.subjects sub on sub.id = grades.subject_id and sub.class_id = c.id
    where s.id = grades.student_id and c.teacher_id = auth.uid()
  )
)
with check (public.is_teacher() and recorded_by = auth.uid());

drop policy if exists results_teacher_assigned_class on public.results;
create policy results_teacher_assigned_class on public.results for all
using (
  public.is_teacher() and exists (
    select 1 from public.students s
    join public.classes c on c.id = s.class_id
    where s.id = results.student_id and c.teacher_id = auth.uid()
  )
)
with check (public.is_teacher() and recorded_by = auth.uid());

drop policy if exists results_admin_all on public.results;
create policy results_admin_all on public.results for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists results_student_read on public.results;
create policy results_student_read on public.results for select using (
  public.is_student() and exists (
    select 1 from public.students s where s.id = results.student_id and s.profile_id = auth.uid()
  )
);

drop policy if exists announcements_authenticated_read on public.announcements;
create policy announcements_authenticated_read on public.announcements for select using (
  auth.uid() is not null and (
    class_id is null or exists (
      select 1 from public.students s where s.class_id = announcements.class_id and s.profile_id = auth.uid()
    ) or exists (
      select 1 from public.classes c where c.id = announcements.class_id and c.teacher_id = auth.uid()
    )
  )
);

create unique index if not exists attendance_student_date_unique on public.attendance(student_id, date);
create index if not exists portal_credentials_type_identifier_idx on public.portal_credentials(credential_type, login_identifier);

-- ===== supabase/migrations/0004_csv_import_compatibility.sql =====
alter table public.students
  add column if not exists gender text,
  add column if not exists parent_name text,
  add column if not exists parent_phone text,
  add column if not exists parent_email text,
  add column if not exists boarding_status text,
  add column if not exists password text;

alter table public.teachers
  add column if not exists staff_id text,
  add column if not exists subject text,
  add column if not exists role text default 'Teaching Staff',
  add column if not exists assigned_class text,
  add column if not exists password text;

create unique index if not exists teachers_staff_id_unique_idx
  on public.teachers(staff_id)
  where staff_id is not null;

alter table public.results
  add column if not exists student_name text,
  add column if not exists class_name text,
  add column if not exists session text,
  add column if not exists subject_name text,
  add column if not exists result_total numeric,
  add column if not exists average numeric,
  add column if not exists overall_percentage numeric,
  add column if not exists position text;

-- ===== supabase/migrations/0005_teachers_table.sql =====
-- Keep the Supabase schema self-contained for teacher registration and portal credentials.
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  full_name text not null,
  email text,
  phone text,
  staff_id text,
  subject text,
  role text not null default 'Teaching Staff',
  assigned_class text,
  password text,
  status text not null default 'Active',
  created_at timestamptz not null default now()
);

alter table public.teachers add column if not exists profile_id uuid references public.profiles(id) on delete set null;
alter table public.teachers add column if not exists full_name text;
alter table public.teachers add column if not exists email text;
alter table public.teachers add column if not exists phone text;
alter table public.teachers add column if not exists staff_id text;
alter table public.teachers add column if not exists subject text;
alter table public.teachers add column if not exists role text default 'Teaching Staff';
alter table public.teachers add column if not exists assigned_class text;
alter table public.teachers add column if not exists password text;
alter table public.teachers add column if not exists status text default 'Active';
alter table public.teachers add column if not exists created_at timestamptz default now();

create unique index if not exists teachers_staff_id_unique_idx
  on public.teachers(staff_id)
  where staff_id is not null;
create index if not exists teachers_profile_id_idx on public.teachers(profile_id);

alter table public.teachers enable row level security;
drop policy if exists teachers_admin_all on public.teachers;
create policy teachers_admin_all on public.teachers
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists teachers_self_read on public.teachers;
create policy teachers_self_read on public.teachers
  for select using (profile_id = auth.uid());

-- ===== supabase/migrations/0006_student_identifier_compatibility.sql =====
-- Standardize student credentials for legacy and fresh Supabase deployments.
-- Keep student_number when it exists so older imports and screens remain readable.
alter table public.students
  add column if not exists admission_number text,
  add column if not exists full_name text,
  add column if not exists password text,
  add column if not exists profile_id uuid;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'students'
      and column_name = 'student_number'
  ) then
    execute $migration$
      update public.students
      set admission_number = student_number
      where admission_number is null
        and student_number is not null
    $migration$;
    execute 'alter table public.students alter column student_number drop not null';
    execute $migration$
      update public.students
      set student_number = admission_number
      where student_number is null
        and admission_number is not null
    $migration$;
  end if;
end
$$;

create unique index if not exists students_admission_number_unique_idx
  on public.students(admission_number)
  where admission_number is not null;

-- Add the profile foreign key when the profiles table is available, without
-- preventing this compatibility migration from running against a legacy DB.
do $$
begin
  if to_regclass('public.profiles') is not null
     and not exists (
       select 1
       from pg_constraint
       where conname = 'students_profile_id_fkey'
         and conrelid = 'public.students'::regclass
     ) then
    alter table public.students
      add constraint students_profile_id_fkey
      foreign key (profile_id) references public.profiles(id) on delete set null;
  end if;
end
$$;

-- ===== supabase/migrations/0007_media_metadata_compatibility.sql =====
-- Add Admin media metadata without deleting or rewriting existing media rows.
alter table public.events
  add column if not exists category text not null default 'Other',
  add column if not exists status text not null default 'Published';

alter table public.gallery_images
  add column if not exists category text not null default 'Other';

create index if not exists events_status_category_idx
  on public.events(status, category);

create index if not exists gallery_images_category_idx
  on public.gallery_images(category);

-- ===== supabase/migrations/0008_result_position_compatibility.sql =====
-- Add optional report-card position metadata without changing existing result rows.
alter table if exists public.results
  add column if not exists position integer;

create index if not exists results_student_position_idx
  on public.results(student_id, position)
  where position is not null;



-- ============================================================
-- Migration 0009: student portal credentials
-- ============================================================
alter table public.students
  add column if not exists password text;

create unique index if not exists students_admission_number_unique_idx
  on public.students(admission_number)
  where admission_number is not null;

-- ===== supabase/migrations/0010_requested_schema_reconciliation.sql =====
-- Adds the requested student fields, subject timestamp, and public content tables
-- for Supabase projects that were created from an older schema.

alter table if exists public.students
  add column if not exists boarding_status text not null default 'Day',
  add column if not exists password text;

alter table if exists public.subjects
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.complaints (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'New',
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_images (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  alt_text text,
  image_url text not null,
  category text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  event_date date not null default current_date,
  category text,
  status text not null default 'Published',
  image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.complaints enable row level security;
alter table public.gallery_images enable row level security;
alter table public.events enable row level security;

drop policy if exists complaints_public_insert on public.complaints;
create policy complaints_public_insert on public.complaints for insert with check (true);
drop policy if exists complaints_admin_all on public.complaints;
create policy complaints_admin_all on public.complaints for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists gallery_public_read on public.gallery_images;
create policy gallery_public_read on public.gallery_images for select using (true);
drop policy if exists gallery_admin_write on public.gallery_images;
create policy gallery_admin_write on public.gallery_images for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists events_public_read on public.events;
create policy events_public_read on public.events for select using (true);
drop policy if exists events_admin_write on public.events;
create policy events_admin_write on public.events for all using (public.is_admin()) with check (public.is_admin());

create index if not exists complaints_status_idx on public.complaints(status);
create index if not exists events_date_idx on public.events(event_date);


-- ===== supabase/migrations/0011_parent_links_payments.sql =====
-- Parent/teacher student links, Paystack result access, and profile compatibility.
alter table if exists public.students add column if not exists profile_id uuid;

do $$
begin
  if to_regclass('public.profiles') is not null
     and not exists (select 1 from pg_constraint where conname = 'students_profile_id_fkey' and conrelid = 'public.students'::regclass) then
    alter table public.students add constraint students_profile_id_fkey foreign key (profile_id) references public.profiles(id) on delete set null;
  end if;
end
$$;
create index if not exists students_profile_id_idx on public.students(profile_id);

create table if not exists public.parent_profiles (
  id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles(id) on delete set null,
  full_name text not null, email text, phone text, status text not null default 'Active', created_at timestamptz not null default now()
);
create table if not exists public.parent_student_links (
  id uuid primary key default gen_random_uuid(), parent_id uuid not null references public.parent_profiles(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade, relationship text not null default 'Parent',
  created_at timestamptz not null default now(), unique(parent_id, student_id)
);
create table if not exists public.teacher_student_links (
  id uuid primary key default gen_random_uuid(), teacher_id bigint not null references public.teachers(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade, relationship text not null default 'Teacher',
  created_at timestamptz not null default now(), unique(teacher_id, student_id)
);
create index if not exists parent_student_links_student_idx on public.parent_student_links(student_id);
create index if not exists teacher_student_links_student_idx on public.teacher_student_links(student_id);

create table if not exists public.result_access_payments (
  id uuid primary key default gen_random_uuid(), student_id bigint not null references public.students(id) on delete cascade,
  reference text not null unique, amount_kobo integer not null default 100000 check (amount_kobo = 100000),
  currency text not null default 'NGN' check (currency = 'NGN'),
  status text not null default 'initialized' check (status in ('initialized', 'success', 'failed')),
  paystack_status text, paid_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.result_access_grants (
  id uuid primary key default gen_random_uuid(), student_id bigint not null references public.students(id) on delete cascade,
  payment_id uuid not null unique references public.result_access_payments(id) on delete cascade,
  granted_at timestamptz not null default now(), expires_at timestamptz, unique(student_id, payment_id)
);
create index if not exists result_access_payments_student_idx on public.result_access_payments(student_id, created_at desc);
create index if not exists result_access_grants_student_idx on public.result_access_grants(student_id, granted_at desc);

alter table public.parent_profiles enable row level security;
alter table public.parent_student_links enable row level security;
alter table public.teacher_student_links enable row level security;
alter table public.result_access_payments enable row level security;
alter table public.result_access_grants enable row level security;
drop policy if exists parent_profiles_admin_all on public.parent_profiles;
create policy parent_profiles_admin_all on public.parent_profiles for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists parent_student_links_admin_all on public.parent_student_links;
create policy parent_student_links_admin_all on public.parent_student_links for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists teacher_student_links_admin_all on public.teacher_student_links;
create policy teacher_student_links_admin_all on public.teacher_student_links for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists result_access_payments_admin_all on public.result_access_payments;
create policy result_access_payments_admin_all on public.result_access_payments for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists result_access_grants_admin_all on public.result_access_grants;
create policy result_access_grants_admin_all on public.result_access_grants for all using (public.is_admin()) with check (public.is_admin());


-- ===== supabase/migrations/0012_school_platform_expansion.sql =====
-- 0012_school_platform_expansion.sql
-- Non-destructive expansion for parent portal, fees, communications, learning,
-- admissions, analytics support, permissions and school operations.
-- No existing school data is deleted.

create table if not exists public.academic_sessions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.terms (
  id bigint generated by default as identity primary key,
  session_id bigint references public.academic_sessions(id) on delete cascade,
  name text not null,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  unique(session_id, name)
);

alter table public.announcements
  add column if not exists audience text not null default 'all',
  add column if not exists target_class_id bigint references public.classes(id) on delete set null,
  add column if not exists target_student_id bigint references public.students(id) on delete cascade,
  add column if not exists pinned boolean not null default false,
  add column if not exists status text not null default 'Published',
  add column if not exists publish_at timestamptz;

create index if not exists announcements_audience_idx on public.announcements(audience, status, pinned);
create index if not exists announcements_target_student_idx on public.announcements(target_student_id);

create table if not exists public.parent_notifications (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.parent_profiles(id) on delete cascade,
  title text not null,
  body text not null,
  type text not null default 'general',
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists parent_notifications_parent_idx on public.parent_notifications(parent_id, created_at desc);

create table if not exists public.parent_notification_preferences (
  parent_id uuid primary key references public.parent_profiles(id) on delete cascade,
  fee_notifications boolean not null default true,
  result_notifications boolean not null default true,
  attendance_notifications boolean not null default true,
  assignment_notifications boolean not null default true,
  event_notifications boolean not null default true,
  message_notifications boolean not null default true,
  whatsapp_notifications boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.parent_messages (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.parent_profiles(id) on delete set null,
  sender_profile_id uuid references public.profiles(id) on delete set null,
  recipient_profile_id uuid references public.profiles(id) on delete set null,
  student_id bigint references public.students(id) on delete set null,
  subject text,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists parent_messages_parent_idx on public.parent_messages(parent_id, created_at desc);
create index if not exists parent_messages_recipient_idx on public.parent_messages(recipient_profile_id, created_at desc);

create table if not exists public.parent_calendar_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  event_date date not null,
  start_time time,
  end_time time,
  audience text not null default 'all',
  class_id bigint references public.classes(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists parent_calendar_events_date_idx on public.parent_calendar_events(event_date);

create table if not exists public.fee_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  default_amount numeric(12,2) not null default 0 check (default_amount >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.fee_invoices (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  session_id bigint references public.academic_sessions(id) on delete set null,
  term_id bigint references public.terms(id) on delete set null,
  invoice_number text not null unique,
  due_date date,
  status text not null default 'Unpaid' check (status in ('Draft','Unpaid','Partially Paid','Paid','Overdue','Cancelled')),
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0),
  balance numeric(12,2) not null default 0 check (balance >= 0),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists fee_invoices_student_idx on public.fee_invoices(student_id, created_at desc);
create index if not exists fee_invoices_status_due_idx on public.fee_invoices(status, due_date);

create table if not exists public.fee_invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.fee_invoices(id) on delete cascade,
  category_id uuid references public.fee_categories(id) on delete set null,
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  created_at timestamptz not null default now()
);
create index if not exists fee_invoice_items_invoice_idx on public.fee_invoice_items(invoice_id);

create table if not exists public.fee_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.fee_invoices(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  parent_id uuid references public.parent_profiles(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  method text not null default 'Paystack',
  reference text unique,
  status text not null default 'Pending' check (status in ('Pending','Confirmed','Failed','Reversed')),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists fee_payments_invoice_idx on public.fee_payments(invoice_id, created_at desc);
create index if not exists fee_payments_student_idx on public.fee_payments(student_id, created_at desc);

create table if not exists public.fee_receipts (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.fee_payments(id) on delete cascade,
  receipt_number text not null unique,
  issued_at timestamptz not null default now()
);

create table if not exists public.student_documents (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  title text not null,
  document_type text not null default 'Other',
  file_url text not null,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists student_documents_student_idx on public.student_documents(student_id, created_at desc);

create table if not exists public.student_promotions (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  from_class_id bigint references public.classes(id) on delete set null,
  to_class_id bigint references public.classes(id) on delete set null,
  from_session_id bigint references public.academic_sessions(id) on delete set null,
  to_session_id bigint references public.academic_sessions(id) on delete set null,
  status text not null default 'Promoted' check (status in ('Promoted','Repeated','Pending')),
  promoted_at timestamptz not null default now(),
  promoted_by uuid references public.profiles(id) on delete set null
);
create index if not exists student_promotions_student_idx on public.student_promotions(student_id, promoted_at desc);

create table if not exists public.result_locks (
  id uuid primary key default gen_random_uuid(),
  class_id bigint references public.classes(id) on delete cascade,
  term_id bigint references public.terms(id) on delete cascade,
  locked boolean not null default true,
  locked_by uuid references public.profiles(id) on delete set null,
  locked_at timestamptz not null default now(),
  unique(class_id, term_id)
);

create table if not exists public.staff_permissions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  permission text not null,
  allowed boolean not null default true,
  unique(profile_id, permission)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_profile_id, created_at desc);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  teacher_id bigint references public.teachers(id) on delete set null,
  class_id bigint references public.classes(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  description text,
  due_date timestamptz,
  max_score numeric(8,2),
  status text not null default 'Published',
  created_at timestamptz not null default now()
);
create index if not exists assignments_class_due_idx on public.assignments(class_id, due_date);

create table if not exists public.assignment_submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  submission_text text,
  file_url text,
  score numeric(8,2),
  feedback text,
  submitted_at timestamptz,
  status text not null default 'Pending',
  unique(assignment_id, student_id)
);

create table if not exists public.learning_materials (
  id uuid primary key default gen_random_uuid(),
  teacher_id bigint references public.teachers(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  description text,
  file_url text not null,
  material_type text not null default 'Resource',
  created_at timestamptz not null default now()
);
create index if not exists learning_materials_class_idx on public.learning_materials(class_id, created_at desc);

create table if not exists public.lesson_plans (
  id uuid primary key default gen_random_uuid(),
  teacher_id bigint references public.teachers(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  objectives text,
  content text,
  lesson_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.admission_applications (
  id uuid primary key default gen_random_uuid(),
  application_number text not null unique,
  applicant_name text not null,
  date_of_birth date,
  gender text,
  class_applied text,
  parent_name text,
  parent_email text,
  parent_phone text,
  address text,
  status text not null default 'Pending' check (status in ('Pending','Under Review','Interview','Approved','Rejected','Converted')),
  notes text,
  interview_date timestamptz,
  interview_notes text,
  student_id bigint references public.students(id) on delete set null,
  reviewed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists admission_applications_status_idx on public.admission_applications(status, created_at desc);
create index if not exists admission_applications_search_idx on public.admission_applications(applicant_name, application_number);

create table if not exists public.admission_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.admission_applications(id) on delete cascade,
  document_type text not null,
  file_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.school_settings (
  id boolean primary key default true,
  school_name text not null default 'D''Blossom Model Private Schools',
  slogan text,
  logo_url text,
  phone text,
  email text,
  address text,
  updated_at timestamptz not null default now()
);

-- Safe defaults for the new access model.
alter table public.parent_notifications enable row level security;
alter table public.parent_notification_preferences enable row level security;
alter table public.parent_messages enable row level security;
alter table public.parent_calendar_events enable row level security;
alter table public.fee_categories enable row level security;
alter table public.fee_invoices enable row level security;
alter table public.fee_invoice_items enable row level security;
alter table public.fee_payments enable row level security;
alter table public.fee_receipts enable row level security;
alter table public.student_documents enable row level security;
alter table public.student_promotions enable row level security;
alter table public.result_locks enable row level security;
alter table public.staff_permissions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.assignments enable row level security;
alter table public.assignment_submissions enable row level security;
alter table public.learning_materials enable row level security;
alter table public.lesson_plans enable row level security;
alter table public.admission_applications enable row level security;
alter table public.admission_documents enable row level security;
alter table public.school_settings enable row level security;

drop policy if exists parent_notifications_self on public.parent_notifications;
create policy parent_notifications_self on public.parent_notifications for select to authenticated using (exists (select 1 from public.parent_profiles p where p.id = parent_notifications.parent_id and p.profile_id = auth.uid()));
drop policy if exists parent_preferences_self on public.parent_notification_preferences;
create policy parent_preferences_self on public.parent_notification_preferences for all to authenticated using (exists (select 1 from public.parent_profiles p where p.id = parent_notification_preferences.parent_id and p.profile_id = auth.uid())) with check (exists (select 1 from public.parent_profiles p where p.id = parent_notification_preferences.parent_id and p.profile_id = auth.uid()));
drop policy if exists parent_messages_self on public.parent_messages;
create policy parent_messages_self on public.parent_messages for select to authenticated using (
  exists (select 1 from public.parent_profiles p where p.id = parent_messages.parent_id and p.profile_id = auth.uid())
  or sender_profile_id = auth.uid() or recipient_profile_id = auth.uid()
);
drop policy if exists parent_calendar_public_read on public.parent_calendar_events;
create policy parent_calendar_public_read on public.parent_calendar_events for select to authenticated using (true);

create policy fee_categories_admin on public.fee_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_invoices_admin on public.fee_invoices for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_invoice_items_admin on public.fee_invoice_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_payments_admin on public.fee_payments for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_receipts_admin on public.fee_receipts for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy student_documents_admin on public.student_documents for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy promotions_admin on public.student_promotions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy result_locks_admin on public.result_locks for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy staff_permissions_admin on public.staff_permissions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy audit_logs_admin on public.audit_logs for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy assignments_admin on public.assignments for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy assignment_submissions_admin on public.assignment_submissions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy learning_materials_admin on public.learning_materials for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy lesson_plans_admin on public.lesson_plans for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admissions_admin on public.admission_applications for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admission_documents_admin on public.admission_documents for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy school_settings_admin on public.school_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Parents need only the rows belonging to their linked students.
create policy fee_invoices_parent_read on public.fee_invoices for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id where l.student_id=fee_invoices.student_id and p.profile_id=auth.uid())
);
create policy fee_invoice_items_parent_read on public.fee_invoice_items for select to authenticated using (
  exists (select 1 from public.fee_invoices i join public.parent_student_links l on l.student_id=i.student_id join public.parent_profiles p on p.id=l.parent_id where i.id=fee_invoice_items.invoice_id and p.profile_id=auth.uid())
);
create policy fee_payments_parent_read on public.fee_payments for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id where l.student_id=fee_payments.student_id and p.profile_id=auth.uid())
);
create policy fee_receipts_parent_read on public.fee_receipts for select to authenticated using (
  exists (select 1 from public.fee_payments fp join public.parent_student_links l on l.student_id=fp.student_id join public.parent_profiles p on p.id=l.parent_id where fp.id=fee_receipts.payment_id and p.profile_id=auth.uid())
);
create policy student_documents_parent_read on public.student_documents for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id where l.student_id=student_documents.student_id and p.profile_id=auth.uid())
);
create policy assignments_parent_read on public.assignments for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id join public.students s on s.id=l.student_id where s.class_id=assignments.class_id and p.profile_id=auth.uid())
);
create policy learning_materials_parent_read on public.learning_materials for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id join public.students s on s.id=l.student_id where s.class_id=learning_materials.class_id and p.profile_id=auth.uid())
);

-- Teachers can manage classroom content for their assigned classes.
create policy assignments_teacher on public.assignments for all to authenticated using (
  exists (select 1 from public.teachers t join public.classes c on c.name=t.assigned_class where t.profile_id=auth.uid() and c.id=assignments.class_id)
) with check (
  exists (select 1 from public.teachers t join public.classes c on c.name=t.assigned_class where t.profile_id=auth.uid() and c.id=assignments.class_id)
);
create policy submissions_student on public.assignment_submissions for all to authenticated using (
  exists (select 1 from public.students s where s.id=assignment_submissions.student_id and s.profile_id=auth.uid())
) with check (
  exists (select 1 from public.students s where s.id=assignment_submissions.student_id and s.profile_id=auth.uid())
);
create policy learning_materials_teacher on public.learning_materials for all to authenticated using (
  exists (select 1 from public.teachers t where t.id=learning_materials.teacher_id and t.profile_id=auth.uid())
) with check (
  exists (select 1 from public.teachers t where t.id=learning_materials.teacher_id and t.profile_id=auth.uid())
);
create policy lesson_plans_teacher on public.lesson_plans for all to authenticated using (
  exists (select 1 from public.teachers t where t.id=lesson_plans.teacher_id and t.profile_id=auth.uid())
) with check (
  exists (select 1 from public.teachers t where t.id=lesson_plans.teacher_id and t.profile_id=auth.uid())
);

create index if not exists students_full_name_search_idx on public.students using gin (to_tsvector('simple', coalesce(full_name,'')));
create index if not exists students_admission_search_idx on public.students(admission_number);
