import{getSupabase,getSession,signOut,esc}from"./supabase.js";import{renderAdvanced}from"./admin-advanced.js";import{renderParentDashboard}from"./parent-dashboard.js";import{renderTeacherPortal}from"./teacher-portal.js";

const role=document.body.dataset.role||"student";
const loginView=document.querySelector("#login-view"),dashboardView=document.querySelector("#dashboard-view"),loginForm=document.querySelector("#login-form"),notice=document.querySelector("#login-notice");
const TERMS=["First Term","Second Term","Third Term"];
const ADMIN_TABS=[["students","Students","🎓"],["teachers","Teachers","👥"],["results","Results","📄"],["parents","Parents","👨‍👩‍👧"],["payments","Payments","💳"],["events","Events","📅"],["gallery","Gallery","🖼️"],["complaints","Complaints","💬"],["admissions","Admissions","📝"],["messages","Parent Messages","✉️"],["subjects","Subjects","📚"],["advanced","School Management / Advanced","🛠️"],["settings","Settings","⚙️"]];
const toast=(m,t="info")=>{const e=document.createElement("div");e.className="toast";e.dataset.type=t;e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),3200)};
const api=async(path,options={})=>{const token=role==="admin"?await adminSession():(await getSession())?.access_token;if(!token)throw Error(role==="admin"?"Your administrator session has expired. Please sign in again.":"Your session has expired. Please sign in again.");const headers={...options.headers,"content-type":"application/json"};if(role==="admin")headers["x-admin-session"]=token;else headers.Authorization="Bearer "+token;const r=await fetch(path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed.");return d};
const setBusy=(b,on,label)=>{if(!b)return;b.disabled=on;if(on)b.dataset.old=b.textContent;b.textContent=on?label:(b.dataset.old||b.textContent)};
const val=(form,n)=>String(new FormData(form).get(n)||"").trim();
const grade=t=>t>=70?"A":t>=60?"B":t>=50?"C":t>=40?"D":"F";
const pill=(s)=>'<span class="pill pill-'+String(s||"").toLowerCase().replace(/\\s/g,"-")+'">'+esc(s||"—")+'</span>';
const modal=(title,body)=>{document.querySelector("#portal-modal")?.remove();const d=document.createElement("div");d.id="portal-modal";d.className="modal-backdrop";d.innerHTML='<div class="modal-card"><div class="section-head"><h2>'+esc(title)+'</h2><button class="icon-btn" id="modal-close" aria-label="Close">✕</button></div>'+body+'</div>';document.body.append(d);document.querySelector("#modal-close").onclick=()=>d.remove();return d};
const formHtml=(fields,submit="Save")=>'<form id="modal-form" class="form-grid">'+fields.join("")+'<div class="form-actions"><button type="button" class="btn btn-outline" id="modal-cancel">Cancel</button><button class="btn navy-btn" type="submit">'+submit+'</button></div></form>';
const input=(name,label,value="",type="text",req=false,extra="")=>'<label class="field">'+esc(label)+(req?" *":"")+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'" '+(req?"required ":"")+extra+'></label>';
const select=(name,label,options,value="",req=false)=>'<label class="field">'+esc(label)+(req?" *":"")+'<select name="'+name+'" '+(req?"required":"")+'><option value="">Select</option>'+options.map(o=>'<option value="'+esc(o.value)+'" '+(String(o.value)===String(value)?"selected":"")+'>'+esc(o.label)+'</option>').join("")+'</select></label>';
const table=(heads,rows)=>'<div class="table-wrap"><table class="data-table"><thead><tr>'+heads.map(x=>'<th>'+x+'</th>').join("")+'</tr></thead><tbody>'+rows+'</tbody></table></div>';
const csvDownload=(name,rows)=>{const text=rows.map(r=>r.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(",")).join("\\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href)};

async function adminSession(){return localStorage.getItem("dblossom_admin_session")||""}
async function login(){
 if(!loginForm)return;loginForm.addEventListener("submit",async e=>{e.preventDefault();loginForm.querySelectorAll("[data-error]").forEach(x=>x.textContent="");notice.textContent="";
  const identifier=val(loginForm,"identifier"),password=val(loginForm,"password");let ok=true;
  if(!identifier){loginForm.querySelector("[data-error=identifier]").textContent=role==="student"?"Admission number is required":role==="teacher"?"Staff ID is required":"Username is required";ok=false}
  if(!password){loginForm.querySelector("[data-error=password]").textContent="Password is required";ok=false}if(!ok)return;
  const b=loginForm.querySelector("button");setBusy(b,true,"Logging in…");
  try{
   if(role==="admin"){
    try{
     const r=await fetch("/api/admin-login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:identifier,password})});
     const d=await r.json().catch(()=>({}));
     if(r.ok&&d.verified&&d.session){
      localStorage.setItem("dblossom_admin_session",d.session);
      window.location.replace("/admin/?dashboard=1");return;
     }
     throw Error(d.error||"Administrator login service is unavailable.");
    }catch(loginError){
     // Presentation-only fallback: no live school data is exposed when verification is unavailable.
     localStorage.removeItem("dblossom_admin_session");
     window.location.replace("/admin");return;
    }
   }
   const sb=await getSupabase();
   const r=await fetch("/api/portal-login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role,identifier})}),d=await r.json().catch(()=>({}));
   if(!r.ok)throw Error(d.error||"Login failed. Please check your details and try again.");
   if(!d.login_email)throw Error(d.error||"Account not found.");
   const{error}=await sb.auth.signInWithPassword({email:d.login_email,password});if(error)throw Error("Incorrect password. Please try again.");
   toast("Welcome!","success");await render();
  }catch(e){notice.className="notice danger";notice.textContent=e.message;toast(e.message,"error")}finally{setBusy(b,false,"")}
 });
}
async function render(){
 const qs=new URLSearchParams(location.search);
 if(role==="admin"){
  const token=await adminSession();
  if(!token){loginView?.classList.remove("hidden");dashboardView?.classList.add("hidden");return}
  loginView?.classList.add("hidden");dashboardView?.classList.remove("hidden");
  try{await api("/api/dashboard-data")}catch(e){} await adminDashboard()
  return;
 }
 const s=await getSession();
 if(!s){loginView?.classList.remove("hidden");dashboardView?.classList.add("hidden");return}
 loginView?.classList.add("hidden");dashboardView?.classList.remove("hidden");try{const qs=new URLSearchParams(location.search);if((role==="student"||role==="parent")&&qs.get("payment")==="verify"&&qs.get("reference")){const vr=await api("/api/paystack-verify?reference="+encodeURIComponent(qs.get("reference")));history.replaceState({},document.title,location.pathname);toast(vr.data?.verified?"Payment verified. Results unlocked for this student.":"Payment is still being verified.","success")}if(role==="admin"){const check=await api("/api/dashboard-data");if(!["admin","super_admin"].includes(String(check.profile?.role)))throw Error("Administrator access is required.");await adminDashboard(check)}else if(role==="student")await studentDashboard();else if(role==="parent")await renderParentDashboard({api,getSession,esc,toast,setBusy,select,input,table,pill});else await teacherDashboard()}catch(e){dashboardView.innerHTML='<div class="dashboard-shell"><div class="notice danger">'+esc(e.message)+'</div></div>'}}
function shell(title,sub,body){return '<header class="portal-dashboard-header"><div class="container"><div class="portal-head-row"><div><h1>'+esc(title)+'</h1><p>'+esc(sub||"")+'</p></div><button id="logout" class="btn btn-outline-light">Logout</button></div></div></header>'+body}
document.addEventListener("click",e=>{if(e.target.id==="logout"){if(role==="admin"){localStorage.removeItem("dblossom_admin_session");location.href="/admin"}else signOut()}});

async function parentDashboard(){
 const p=await api("/api/parent-data");
 const children=p.children||[], invoices=p.invoices||[], payments=p.payments||[], announcements=p.announcements||[], notifications=p.notifications||[], messages=p.messages||[], events=p.events||[];
 const childOptions=children.map(x=>({value:x.id,label:x.full_name+" — "+(x.class_name||"Class not assigned")}));
 let body='<div class="dashboard-shell"><div class="stats"><article class="stat"><small>Children linked</small><strong>'+children.length+'</strong></article><article class="stat"><small>Outstanding fees</small><strong>₦'+Number(invoices.reduce((a,x)=>a+Number(x.balance||0),0)).toLocaleString()+'</strong></article><article class="stat"><small>Unread notifications</small><strong>'+notifications.filter(x=>!x.read_at).length+'</strong></article></div>';
 body+='<section class="dashboard-card"><div class="section-head"><div><p class="section-label">My Children</p><h2>Parent Academic Dashboard</h2></div></div>'+(children.length?'<div class="cards three">'+children.map(x=>'<article class="card"><h3>'+esc(x.full_name)+'</h3><p>'+esc(x.class_name||"Class not assigned")+'</p><p>Admission No: '+esc(x.admission_number)+'</p><p>Status: '+pill(x.status)+'</p></article>').join("")+'</div>':'<div class="notice">No student has been linked to this parent account yet. Please contact the school administrator.</div>')+'</section>';
 body+='<section class="dashboard-card"><div class="section-head"><div><p class="section-label">Fees</p><h2>Fee Balance & Payment History</h2></div></div>';
 body+=invoices.length?table(["Invoice","Student","Due Date","Total","Paid","Balance","Status"],invoices.map(x=>'<tr><td>'+esc(x.invoice_number)+'</td><td>'+esc(x.student_name)+'</td><td>'+esc(x.due_date||"—")+'</td><td>₦'+Number(x.total_amount||0).toLocaleString()+'</td><td>₦'+Number(x.amount_paid||0).toLocaleString()+'</td><td>₦'+Number(x.balance||0).toLocaleString()+'</td><td>'+pill(x.status)+'</td></tr>').join("")):'<p class="muted">No fee invoices found.</p>';
 body+='</section><section class="dashboard-grid"><section class="dashboard-card"><h2>Announcements</h2>'+(announcements.length?announcements.map(x=>'<article class="notice">'+(x.pinned?'<strong>📌 Pinned</strong> ':'')+'<strong>'+esc(x.title)+'</strong><p>'+esc(x.body)+'</p></article>').join(""):'<p class="muted">No announcements.</p>')+'</section><section class="dashboard-card"><h2>Notifications</h2>'+(notifications.length?notifications.map(x=>'<article class="notice"><strong>'+esc(x.title)+'</strong><p>'+esc(x.body)+'</p></article>').join(""):'<p class="muted">No notifications.</p>')+'</section></div>';
 body+='<section class="dashboard-grid"><section class="dashboard-card"><h2>Parent–School Messages</h2><form id="parent-message-form" class="form-grid">'+input("subject","Subject","")+input("body","Message","", "text",true,'maxlength="2000"')+'<button class="btn navy-btn">Send Message</button></form><div class="message-list">'+(messages.length?messages.map(x=>'<article class="notice"><strong>'+esc(x.subject||"School message")+'</strong><p>'+esc(x.body)+'</p><small>'+esc(x.created_at)+'</small></article>').join(""):'<p class="muted">No messages yet.</p>')+'</div></section><section class="dashboard-card"><h2>Parent Calendar</h2>'+(events.length?events.map(x=>'<article class="notice"><strong>'+esc(x.title)+'</strong><p>'+esc(x.event_date)+' '+esc(x.start_time||"")+'</p><p>'+esc(x.description||"")+'</p></article>').join(""):'<p class="muted">No calendar events.</p>')+'</section></div>';
 body+='<section class="dashboard-card"><h2>Payment History</h2>'+(payments.length?table(["Date","Amount","Method","Reference","Status"],payments.map(x=>'<tr><td>'+esc(x.created_at)+'</td><td>₦'+Number(x.amount||0).toLocaleString()+'</td><td>'+esc(x.method)+'</td><td>'+esc(x.reference||"—")+'</td><td>'+pill(x.status)+'</td></tr>').join("")):'<p class="muted">No payments recorded.</p>')+'</section></div>';
 dashboardView.innerHTML=shell("Welcome, "+esc(p.parent?.full_name||"Parent"),"Parent Portal",body);
 document.querySelector("#parent-message-form")?.addEventListener("submit",async e=>{e.preventDefault();try{await api("/api/parent-data",{method:"POST",body:JSON.stringify({type:"message",subject:val(e.target,"subject"),body:val(e.target,"body")})});toast("Message sent to the school.","success");await parentDashboard()}catch(x){toast(x.message,"error")}});
}

async function studentDashboard(){
 const p=await api("/api/dashboard-data"),s=p.student||{},grades=p.grades||[],attendance=p.attendance||[],ann=p.announcements||[],matches=p.resultMatches||[],assignments=p.assignments||[],materials=p.materials||[];
 const tabs=[["dashboard","Dashboard","📊"],["results","Results","📄"],["attendance","Attendance","🗓️"],["assignments","Assignments","📝"],["materials","Learning Materials","📚"],["announcements","Announcements","📢"],["profile","My Profile","👤"]];
 const body='<div class="dashboard-shell"><div class="stats"><article class="stat"><small>Student</small><strong>'+esc(s.full_name||"—")+'</strong></article><article class="stat"><small>Class</small><strong>'+esc(s.class_name||"—")+'</strong></article><article class="stat"><small>Results Available</small><strong>'+matches.length+'</strong></article></div><div class="admin-layout"><aside class="admin-sidebar">'+tabs.map((x,i)=>'<button class="student-tab admin-tab '+(i?"":"active")+'" data-tab="'+x[0]+'"><span>'+x[2]+'</span>'+x[1]+'</button>').join("")+'</aside><div class="admin-content" id="student-panel"></div></div><nav class="admin-bottom-nav">'+tabs.map((x,i)=>'<button class="student-tab admin-tab '+(i?"":"active")+'" data-tab="'+x[0]+'"><span>'+x[2]+'</span>'+x[1]+'</button>').join("")+'</nav></div>';
 dashboardView.innerHTML=shell("Welcome, "+(s.full_name||"Student"),(s.class_name||"Class not assigned")+" | Admission No: "+(s.admission_number||"—"),body);
 const panel=document.querySelector("#student-panel");
 const open=tab=>{document.querySelectorAll(".student-tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));if(tab==="dashboard")studentOverview(panel,s,grades,matches,assignments,attendance);if(tab==="results")studentResults(panel,s,p,grades,matches);if(tab==="attendance")studentAttendance(panel,attendance);if(tab==="assignments")studentAssignments(panel,assignments);if(tab==="materials")studentMaterials(panel,materials);if(tab==="announcements")studentAnnouncements(panel,ann);if(tab==="profile")studentProfile(panel,s)};
 document.querySelectorAll(".student-tab").forEach(x=>x.onclick=()=>open(x.dataset.tab));open("dashboard");
}
function studentOverview(panel,s,grades,matches,assignments,attendance){panel.innerHTML='<section class="dashboard-card"><p class="section-label">Student Portal</p><h2>My Academic Dashboard</h2><p class="muted">Your class resources, attendance, assignments and result access are shown here.</p><div class="cards three"><article class="card"><h3>'+matches.length+'</h3><p>Result term/session combinations</p></article><article class="card"><h3>'+assignments.length+'</h3><p>Class assignments</p></article><article class="card"><h3>'+attendance.length+'</h3><p>Attendance records</p></article></div><div class="notice"><strong>Result checking</strong><p>Find your term and session first. If the result exists, the portal will show “Result found” before requesting the ₦1,000 Paystack access payment.</p></div></section>'}
function studentResults(panel,s,p,grades,matches){
 panel.innerHTML='<section class="dashboard-card"><div class="section-head"><div><p class="section-label">Academic Records</p><h2>Check Result</h2></div><span class="notice-inline">'+(p.hasResultAccess?"Payment confirmed":"₦1,000 access")+'</span></div><div class="result-filters">'+select("term","Term",TERMS.map(x=>({value:x,label:x})))+input("session","Session","","text",true,'placeholder="e.g. 2026/2027"')+'<button class="btn navy-btn" id="find-result">Find Result</button></div><div id="result-output"><p class="muted">Enter term and session to check whether your result is available.</p></div></section>';
 panel.querySelector("#find-result").onclick=async()=>{const term=panel.querySelector('[name="term"]').value,session=panel.querySelector('[name="session"]').value.trim(),out=panel.querySelector("#result-output");if(!term||!session)return toast("Please select term and session.","error");const found=matches.some(x=>x.term===term&&x.session===session);if(!found){out.innerHTML='<div class="notice danger">No result was found for '+esc(term)+" / "+esc(session)+".</div>";return}if(!p.hasResultAccess){out.innerHTML='<div class="notice"><strong>Result found.</strong><p>Your result is available. Pay ₦1,000 securely with Paystack to view it.</p><button class="btn btn-gold" id="pay-results">Pay ₦1,000 & View Result</button></div>';panel.querySelector("#pay-results").onclick=async()=>{const btn=panel.querySelector("#pay-results");setBusy(btn,true,"Opening secure payment…");try{const ss=await getSession(),r=await fetch("/api/paystack-init",{method:"POST",headers:{Authorization:"Bearer "+ss.access_token,"x-idempotency-key":crypto.randomUUID()}}),d=await r.json();if(!r.ok)throw Error(d.error||"Payment could not be started.");location.href=d.data.authorization_url}catch(e){toast(e.message,"error");setBusy(btn,false,"")}};return}const rows=grades.filter(x=>x.term===term&&x.session===session);out.innerHTML=rows.length?report(rows,s):'<div class="notice danger">Payment is confirmed, but the result records are not available.</div>';out.querySelector("#download-pdf")?.addEventListener("click",downloadPdf)};
}
function studentAttendance(panel,rows){panel.innerHTML='<section class="dashboard-card"><h2>My Attendance</h2>'+(rows.length?table(["Date","Status"],rows.map(x=>'<tr><td>'+esc(x.date)+'</td><td>'+pill(x.status)+'</td></tr>').join("")):'<p class="muted">No attendance records have been recorded yet.</p>')+'</section>'}
function studentAssignments(panel,rows){panel.innerHTML='<section class="dashboard-card"><h2>Assignments</h2>'+(rows.length?table(["Title","Subject","Due Date","Max Score","Status"],rows.map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+esc(x.subject_name||"—")+'</td><td>'+esc(x.due_date||"—")+'</td><td>'+esc(x.max_score??"—")+'</td><td>'+pill(x.status||"Published")+'</td></tr>').join("")):'<p class="muted">No assignments have been posted for your class.</p>')+'</section>'}
function studentMaterials(panel,rows){panel.innerHTML='<section class="dashboard-card"><h2>Learning Materials</h2>'+(rows.length?table(["Title","Subject","Type","Resource"],rows.map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+esc(x.subject_name||"—")+'</td><td>'+esc(x.material_type||"Resource")+'</td><td>'+(x.file_url?'<a class="btn btn-sm btn-outline" href="'+esc(x.file_url)+'" target="_blank" rel="noopener">Open</a>':"—")+'</td></tr>').join("")):'<p class="muted">No learning materials have been posted for your class.</p>')+'</section>'}
function studentAnnouncements(panel,rows){panel.innerHTML='<section class="dashboard-card"><h2>Announcements</h2>'+(rows.length?rows.map(x=>'<article class="notice"><strong>'+esc(x.title)+'</strong><p>'+esc(x.body)+'</p><small>'+esc(x.created_at||"")+'</small></article>').join(""):'<p class="muted">No announcements.</p>')+'</section>'}
function studentProfile(panel,s){panel.innerHTML='<section class="dashboard-card"><h2>My Profile</h2>'+table(["Field","Value"],[["Full Name",s.full_name],["Admission Number",s.admission_number],["Class",s.class_name],["Guardian",s.guardian_name]].map(x=>'<tr><td>'+esc(x[0])+'</td><td>'+esc(x[1]||"—")+'</td></tr>').join(""))+'</section>'}
function report(rows,s){const total=rows.reduce((a,x)=>a+Number(x.total_score||0),0),avg=rows.length?Math.round(total/rows.length*100)/100:0,first=rows[0];return '<div class="report-actions"><button class="btn btn-outline" id="download-pdf">⇩ Download Result (PDF)</button></div><div class="report-wrap" id="report-card"><div class="report-header"><img src="/logo.jpg" alt="D’Blossom"><div><h2>D’Blossom Model Private Schools</h2><p>Abeokuta, Ogun State, Nigeria</p><em>Building Tomorrow’s Leaders</em></div></div><div class="report-title">STUDENT ACADEMIC REPORT</div><div class="report-info"><div><small>Student Name</small><strong>'+esc(s.full_name)+'</strong></div><div><small>Admission No.</small><strong>'+esc(s.admission_number)+'</strong></div><div><small>Class</small><strong>'+esc(s.class_name||"—")+'</strong></div><div><small>Term / Session</small><strong>'+esc(first.term)+" / "+esc(first.session)+'</strong></div></div>'+table(["Subject","CA Score","Exam Score","Total","Grade"],rows.map(x=>'<tr><td>'+esc(x.subject_name||"Subject")+'</td><td>'+esc(x.ca_score??"—")+'</td><td>'+esc(x.exam_score??"—")+'</td><td>'+esc(x.total_score??"0")+'</td><td>'+pill(x.grade)+'</td></tr>').join(""))+'<div class="report-summary"><div><small>Total Score</small><strong>'+total+'</strong></div><div><small>Average</small><strong>'+avg+'</strong></div><div><small>Position</small><strong>—</strong></div></div><div class="report-comments"><p><b>Teacher’s Comment:</b> '+esc([...new Set(rows.map(x=>x.teacher_comment).filter(Boolean))].join(" ")||"No teacher comment.")+'</p><p><b>Principal’s Comment:</b> '+esc([...new Set(rows.map(x=>x.principal_comment).filter(Boolean))].join(" ")||"No principal comment.")+'</p></div></div>'}
async function downloadPdf(){const el=document.querySelector("#report-card");if(!el)return;try{await load("https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js","html2canvas");await load("https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js","jspdf");const canvas=await window.html2canvas(el,{scale:2,backgroundColor:"#fff",useCORS:true}),{jsPDF}=window.jspdf,pdf=new jsPDF("p","mm","a4"),w=210,page=297,h=canvas.height*w/canvas.width;let left=h,y=0,img=canvas.toDataURL("image/png");pdf.addImage(img,"PNG",0,y,w,h);left-=page;while(left>0){y-=page;pdf.addPage();pdf.addImage(img,"PNG",0,y,w,h);left-=page}pdf.save("D-Blossom-Result.pdf")}catch(e){toast("PDF could not be generated. Please try again.","error")}}
const load=(src,key)=>new Promise((ok,no)=>{if(window[key])return ok();const s=document.createElement("script");s.src=src;s.onload=ok;s.onerror=no;document.head.append(s)});

async function teacherDashboard(){await renderTeacherPortal(dashboardView,shell)}

async function adminDashboard(){
 dashboardView.innerHTML=shell("D’Blossom Administrator","School Management System",'<div class="dashboard-shell"><div class="admin-layout"><aside class="admin-sidebar">'+ADMIN_TABS.map((x,i)=>'<button class="admin-tab '+(i===0?"active":"")+'" data-tab="'+x[0]+'"><span>'+x[2]+'</span>'+x[1]+'</button>').join("")+'</aside><div class="admin-content" id="admin-panel"></div></div><nav class="admin-bottom-nav">'+ADMIN_TABS.map((x,i)=>'<button class="admin-tab '+(i===0?"active":"")+'" data-tab="'+x[0]+'"><span>'+x[2]+'</span>'+x[1]+'</button>').join("")+'</nav></div>');
 const panel=document.querySelector("#admin-panel");
 const open=async tab=>{document.querySelectorAll(".admin-tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));await renderAdminTab(tab,panel)};
 document.querySelectorAll(".admin-tab").forEach(b=>b.onclick=()=>open(b.dataset.tab));
 await open("students");
}

async function adminGet(table,params={}){const u=new URL("/api/admin-operations",location.origin);u.searchParams.set("table",table);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,v));return api(u.pathname+u.search)}
async function adminPost(body){return api("/api/admin-operations",{method:"POST",body:JSON.stringify(body)})}
async function renderAdminTab(tab,panel){try{panel.innerHTML='<div class="dashboard-card"><p class="muted">Loading '+esc(tab)+'…</p></div>';if(tab==="students")return adminStudents(panel);if(tab==="teachers")return adminTeachers(panel);if(tab==="parents")return adminParents(panel);if(tab==="results")return adminResults(panel);if(tab==="payments")return adminPayments(panel);if(tab==="events")return adminEvents(panel);if(tab==="gallery")return adminGallery(panel);if(tab==="complaints")return adminComplaints(panel);if(tab==="admissions")return adminAdmissions(panel);if(tab==="messages")return adminMessages(panel);if(tab==="subjects")return adminSubjects(panel);if(tab==="advanced")return renderAdvanced(panel,{api,esc,modal,formHtml,input,select,table,pill,csvDownload,toast,setBusy});return adminSettings(panel)}catch(e){panel.innerHTML='<div class="notice danger">'+esc(e.message)+'</div>'}}
function adminSectionTools(panel,placeholder,filters=[]){if(panel.querySelector("[data-admin-tools]"))return;const bar=document.createElement("div");bar.className="admin-list-tools";bar.dataset.adminTools="1";bar.style.marginBottom="1rem";bar.innerHTML='<input data-admin-search placeholder="'+esc(placeholder||"Search this section...")+'"><select data-admin-filter><option value="">All</option>'+filters.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("")+'</select>';panel.prepend(bar);const apply=()=>{const q=bar.querySelector("[data-admin-search]").value.toLowerCase(),f=bar.querySelector("[data-admin-filter]").value.toLowerCase();panel.querySelectorAll(".data-table tbody tr,.gallery-admin-card,.complaint-card,.message-list > article,.subject-row,.dashboard-card").forEach(el=>{const t=el.textContent.toLowerCase();el.style.display=(!q||t.includes(q))&&(!f||t.includes(f))?"":"none"})};bar.querySelector("[data-admin-search]").oninput=apply;bar.querySelector("[data-admin-filter]").onchange=apply;}async function adminStudents(panel,params={}){
 const page=Math.max(1,Number(params.page||1)),pageSize=100,query={page,pageSize,q:params.q||"",class_id:params.class_id||""},r=await adminGet("students",query),classes=(await adminGet("classes")).data||[];
 const rows=r.data||[],total=Number(r.count||rows.length),totalPages=Math.max(1,Math.ceil(total/pageSize));
 panel.innerHTML='<div class="section-head"><div><p class="section-label">Students</p><h2>Manage Students</h2><p class="muted">'+total.toLocaleString()+' student(s) in the school · All student records are loaded from Supabase.</p></div><div class="admin-list-tools"><input id="student-search" value="'+esc(params.q||"")+'" placeholder="Search name, admission no., guardian or contact"><select id="student-class-filter"><option value="">All classes</option>'+classes.map(x=>'<option value="'+x.id+'" '+(String(x.id)===String(params.class_id||"")?"selected":"")+'>'+esc(x.name)+'</option>').join("")+'</select><button class="btn btn-outline" id="export-students">⇩ CSV</button><button class="btn navy-btn" id="add-student">+ Add Student</button></div></div>'+table(["Name","Admission No.","Class","Status","Actions"],rows.map(x=>'<tr><td>'+esc(x.full_name)+'</td><td>'+esc(x.admission_number)+'</td><td>'+esc(x.class_name)+'</td><td>'+pill(x.status)+'</td><td><button class="btn btn-sm btn-outline view-student" data-id="'+x.id+'">View Details</button> <button class="btn btn-sm btn-outline edit-student" data-id="'+x.id+'">Edit</button> <button class="btn btn-sm danger-btn delete-record" data-table="students" data-id="'+x.id+'">Delete</button></td></tr>').join(""))+'<div class="form-actions">'+(totalPages>1?'<button class="btn btn-outline" id="student-prev" '+(page<=1?"disabled":"")+'>← Previous</button><span class="muted">Page '+page+' of '+totalPages+'</span><button class="btn btn-outline" id="student-next" '+(page>=totalPages?"disabled":"")+'>Next →</button>': '<span class="muted">Showing all '+total.toLocaleString()+' students</span>')+'</div>';
 const reload=p=>adminStudents(panel,{page:p,q:panel.querySelector("#student-search").value,class_id:panel.querySelector("#student-class-filter").value});
 panel.querySelector("#student-search").oninput=e=>{clearTimeout(window.__studentSearchTimer);window.__studentSearchTimer=setTimeout(()=>reload(1),300)};
 panel.querySelector("#student-class-filter").onchange=()=>reload(1);
 panel.querySelector("#student-prev")?.addEventListener("click",()=>reload(page-1));
 panel.querySelector("#student-next")?.addEventListener("click",()=>reload(page+1));
 panel.querySelector("#add-student").onclick=()=>studentModal(classes);
 panel.querySelectorAll(".view-student").forEach(b=>b.onclick=()=>studentDetailsModal(rows.find(x=>x.id===b.dataset.id)));
 panel.querySelectorAll(".edit-student").forEach(b=>b.onclick=()=>studentModal(classes,rows.find(x=>x.id===b.dataset.id)));
 panel.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>deleteRecord("students",b.dataset.id,()=>reload(page)));
 panel.querySelector("#export-students").onclick=async()=>{const all=[],pages=Math.max(1,Math.ceil(total/1000));for(let p=1;p<=pages;p++){const chunk=await adminGet("students",{page:p,pageSize:100,q:panel.querySelector("#student-search").value,class_id:panel.querySelector("#student-class-filter").value});all.push(...(chunk.data||[]))}csvDownload("students.csv",[["Full Name","Admission Number","Class","Date of Birth","Gender","Guardian Name","Guardian Contact","Parent Email","Boarding Status","Status","Created At"],...all.map(x=>[x.full_name,x.admission_number,x.class_name,x.date_of_birth,x.gender,x.guardian_name,x.guardian_contact,x.parent_email,x.boarding_status,x.status,x.created_at])])}
}
function studentDetailsModal(x={}){
 if(!x)return toast("Student record could not be found.","error");
 const field=(label,value)=>'<div class="card"><small class="muted">'+esc(label)+'</small><strong>'+esc(value||"—")+'</strong></div>';
 const body='<div class="cards three">'+
 field("Full Name",x.full_name)+field("Admission Number",x.admission_number)+field("Class",x.class_name)+
 field("Date of Birth",x.date_of_birth)+field("Gender",x.gender)+field("Status",x.status)+
 field("Parent / Guardian",x.guardian_name)+field("Guardian Contact",x.guardian_contact)+field("Parent Email",x.parent_email)+field("Login Admission Number",x.admission_number)+field("Login Password","Password is securely stored in Supabase Auth; the existing password cannot be retrieved or displayed.")+
 field("Boarding Status",x.boarding_status)+field("Student ID",x.id)+field("Profile ID",x.profile_id)+field("Created At",x.created_at)+
 '</div><div class="form-actions"><button class="btn btn-outline" id="student-details-close">Close</button></div>';
 const m=modal("Student Details — "+(x.full_name||"Student"),body);
 m.querySelector("#student-details-close").onclick=()=>m.remove();
}
function studentModal(classes,x={}){const m=modal(x.id?"Edit Student":"Add Student",formHtml([input("full_name","Full Name",x.full_name||"", "text",true),input("admission_number","Admission Number",x.admission_number||"", "text",true),select("class_id","Class",classes.map(c=>({value:c.id,label:c.name})),x.class_id||"",false),input("date_of_birth","Date of Birth",x.date_of_birth||"","date"),select("gender","Gender",[{value:"Male",label:"Male"},{value:"Female",label:"Female"}],x.gender||""),input("guardian_name","Parent / Guardian Name",x.guardian_name||""),input("guardian_contact","Parent Phone",x.guardian_contact||""),input("parent_email","Parent Email",x.parent_email||"","email"),select("boarding_status","Boarding Status",[{value:"Day",label:"Day"},{value:"Boarding",label:"Boarding"}],x.boarding_status||""),input("password","Portal Password","","password",!x.id,'minlength="6"'),select("status","Status",[{value:"active",label:"Active"},{value:"graduated",label:"Graduated"},{value:"withdrawn",label:"Withdrawn"}],x.status||"active",true)],x.id?"Update Student":"Create Student"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{const f=e.target,d=Object.fromEntries(new FormData(f));await adminPost({type:"student",id:x.id,...d});m.remove();toast("Student saved.","success");adminStudents(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}}}
async function adminTeachers(panel){
 const r=await adminGet("teachers",{page:1,pageSize:1000}),classes=(await adminGet("classes")).data||[],subjects=(await adminGet("subjects",{page:1,pageSize:200})).data||[];
 panel.innerHTML='<div class="section-head"><div><p class="section-label">Teachers</p><h2>Manage Teachers</h2><p class="muted">Assign each teacher to the class and subject they are responsible for.</p></div><div><button class="btn btn-outline" id="export-teachers">⇩ CSV</button> <button class="btn navy-btn" id="add-teacher">+ Add Teacher</button></div></div>'+table(["Name","Staff ID","Role","Class","Subject","Status","Actions"],r.data.map(x=>'<tr><td>'+esc(x.full_name)+'</td><td>'+esc(x.staff_id)+'</td><td>'+pill(x.role)+'</td><td>'+esc(x.class_name||x.assigned_class||"—")+'</td><td>'+esc(x.subject_name||x.subject||"—")+'</td><td>'+pill(x.status)+'</td><td><button class="btn btn-sm btn-outline edit-teacher" data-id="'+x.id+'">Edit</button> <button class="btn btn-sm danger-btn delete-record" data-table="teachers" data-id="'+x.id+'">Delete</button></td></tr>').join(""));
 document.querySelector("#add-teacher").onclick=()=>teacherModal(classes,subjects);
 document.querySelectorAll(".edit-teacher").forEach(b=>b.onclick=()=>teacherModal(classes,subjects,r.data.find(x=>x.id===b.dataset.id)));
 document.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>deleteRecord("teachers",b.dataset.id,()=>adminTeachers(panel)));
 document.querySelector("#export-teachers").onclick=()=>csvDownload("teachers.csv",[["Full Name","Staff ID","Email","Phone","Subject","Role","Assigned Class","Status"],...r.data.map(x=>[x.full_name,x.staff_id,x.email,x.phone,x.subject_name||x.subject,x.role,x.class_name||x.assigned_class,x.status])]);adminSectionTools(panel,"Search teachers...",["Active","Disabled","Class Teacher","Teaching Staff"]);
}
function teacherModal(classes,subjects,x={}){
 const m=modal(x.id?"Edit Teacher":"Add Teacher",formHtml([
 input("full_name","Full Name",x.full_name||"","text",true),
 input("staff_id","Staff ID",x.staff_id||"","text",true),
 input("email","Email",x.email||"","email"),
 input("phone","Phone",x.phone||""),
 select("class_id","Assigned Class",classes.map(c=>({value:c.id,label:c.name})),x.class_id||"",false),
 select("subject_id","Assigned Subject",subjects.map(s=>({value:s.id,label:s.name+(s.class_id?"":" — General")})),x.subject_id||"",false),
 select("role","Role",[{value:"Class Teacher",label:"Class Teacher"},{value:"Teaching Staff",label:"Teaching Staff"}],x.role||"Teaching Staff",true),
 input("password","Portal Password","","password",!x.id,'minlength="6"'),
 select("status","Status",[{value:"active",label:"Active"},{value:"disabled",label:"Disabled"}],x.status||"active",true)
 ],x.id?"Update Teacher":"Create Teacher"));
 m.querySelector("#modal-cancel").onclick=()=>m.remove();
 m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{await adminPost({type:"teacher",id:x.id,...Object.fromEntries(new FormData(e.target))});m.remove();toast("Teacher saved.","success");adminTeachers(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}}
}
async function adminParents(panel,params={}){const r=await adminGet("parents",{page:1,pageSize:100,...params}),students=(await adminGet("students",{page:1,pageSize:200})).data||[];const rows=r.data||[];panel.innerHTML='<div class="section-head"><div><p class="section-label">Parents</p><h2>Manage Parents</h2><p class="muted">Create parent portal accounts, update contact details and link parents to their children.</p></div><div class="admin-list-tools"><input id="parent-search" placeholder="Search name, email or phone"><select id="parent-status-filter"><option value="">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select><button class="btn btn-outline" id="export-parents">⇩ CSV</button><button class="btn navy-btn" id="add-parent">+ Add Parent</button></div></div>'+table(["Name","Email","Phone","Children","Status","Actions"],rows.map(x=>'<tr><td>'+esc(x.full_name||"—")+'</td><td>'+esc(x.email||"—")+'</td><td>'+esc(x.phone||"—")+'</td><td>'+esc((x.children||[]).map(s=>s.full_name).join(", ")||"None")+'</td><td>'+pill(x.status||"active")+'</td><td><button class="btn btn-sm btn-outline edit-parent" data-id="'+x.id+'">Edit</button> <button class="btn btn-sm danger-btn delete-parent" data-id="'+x.id+'">Delete</button></td></tr>').join(""));const search=document.querySelector("#parent-search"),status=document.querySelector("#parent-status-filter");const reload=()=>adminParents(panel,{q:search.value,status:status.value});search.oninput=()=>{clearTimeout(window.__parentSearchTimer);window.__parentSearchTimer=setTimeout(reload,300)};status.onchange=reload;document.querySelector("#add-parent").onclick=()=>parentModal(students);document.querySelectorAll(".edit-parent").forEach(b=>b.onclick=()=>parentModal(students,rows.find(x=>x.id===b.dataset.id)));document.querySelectorAll(".delete-parent").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this parent account?"))return;try{await adminPost({type:"parent",action:"delete",id:b.dataset.id});toast("Parent deleted.","success");adminParents(panel)}catch(e){toast(e.message,"error")}});document.querySelector("#export-parents").onclick=()=>csvDownload("parents.csv",[["Name","Email","Phone","Children","Status"],...rows.map(x=>[x.full_name,x.email,x.phone,(x.children||[]).map(s=>s.full_name).join(", "),x.status])]);}
function parentModal(students,x={}){const linked=new Set((x.children||[]).map(s=>s.id));const m=modal(x.id?"Edit Parent":"Add Parent",formHtml([input("full_name","Full Name",x.full_name||"","text",true),input("email","Email",x.email||"","email",true),input("phone","Phone",x.phone||""),input("address","Address",x.address||""),input("occupation","Occupation",x.occupation||""),input("password","Portal Password","","password",!x.id,'minlength="6"'),select("status","Status",[{value:"active",label:"Active"},{value:"disabled",label:"Disabled"}],x.status||"active",true),'<label class="field">Children<select name="student_ids" multiple size="6">'+students.map(s=>'<option value="'+s.id+'" '+(linked.has(s.id)?"selected":"")+'>'+esc(s.full_name)+' — '+esc(s.admission_number)+'</option>').join("")+'</select><small class="muted">Hold Ctrl/Cmd to select multiple children.</small></label>'],"Save Parent"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),ids=f.getAll("student_ids");const data={type:"parent",id:x.id,full_name:f.get("full_name"),email:f.get("email"),phone:f.get("phone"),address:f.get("address"),occupation:f.get("occupation"),password:f.get("password"),status:f.get("status"),student_ids:ids};await adminPost(data);m.remove();toast("Parent saved.","success");adminParents(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}};}
async function adminResults(panel,filters={}){const r=await adminGet("results",{page:1,pageSize:100,term:filters.term||"",class_id:filters.class_id||""}),students=(await adminGet("students",{page:1,pageSize:100})).data||[],subjects=(await adminGet("subjects",{page:1,pageSize:100})).data||[],terms=(await adminGet("terms")).data||[];panel.innerHTML='<div class="section-head"><div><p class="section-label">Results</p><h2>Manage Results</h2></div><div class="admin-list-tools"><select id="result-class"><option value="">All classes</option>'+students.map(s=>s.class_id?'<option value="'+s.class_id+'">'+esc(s.class_name||"Class")+'</option>':"").filter((x,i,a)=>x&&a.indexOf(x)===i).join("")+'</select><select id="result-term-filter"><option value="">All terms</option>'+TERMS.map(t=>'<option>'+t+'</option>').join("")+'</select><button class="btn btn-outline" id="export-results">⇩ CSV</button><button class="btn navy-btn" id="add-result">+ Add Result</button></div></div>'+table(["Student","Class","Term","Session","Subject","CA","Exam","Total","Grade","Actions"],r.data.map(x=>'<tr><td>'+esc(x.students?.full_name)+'</td><td>'+esc(x.students?.classes?.name||"—")+'</td><td>'+esc(x.terms?.name||"—")+'</td><td>'+esc(x.terms?.academic_sessions?.name||"—")+'</td><td>'+esc(x.subjects?.name||"—")+'</td><td>'+x.ca_score+'</td><td>'+x.exam_score+'</td><td>'+x.total_score+'</td><td>'+pill(x.grade)+'</td><td><button class="btn btn-sm btn-outline edit-result" data-id="'+x.id+'">Edit</button> <button class="btn btn-sm danger-btn delete-record" data-table="results" data-id="'+x.id+'">Delete</button></td></tr>').join(""));document.querySelector("#result-class").onchange=e=>adminResults(panel,{class_id:e.target.value,term:document.querySelector("#result-term-filter").value});document.querySelector("#result-term-filter").onchange=e=>adminResults(panel,{class_id:document.querySelector("#result-class").value,term:e.target.value});document.querySelector("#export-results").onclick=()=>csvDownload("results.csv",[["Student Name","Class","Term","Session","Subject","CA Score","Exam Score","Total","Grade","Teacher Comment","Principal Comment"],...r.data.map(x=>[x.students?.full_name,x.students?.classes?.name,x.terms?.name,x.terms?.academic_sessions?.name,x.subjects?.name,x.ca_score,x.exam_score,x.total_score,x.grade,x.teacher_comment,x.principal_comment])]);adminSectionTools(panel,"Search results by student, subject or class...",["A","B","C","D","F"]);document.querySelector("#add-result").onclick=()=>resultModal(students,subjects,terms);document.querySelectorAll(".edit-result").forEach(b=>b.onclick=()=>resultModal(students,subjects,terms,r.data.find(x=>x.id===b.dataset.id)));document.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>deleteRecord("results",b.dataset.id,()=>adminResults(panel)))}
function resultModal(students,subjects,terms,x={}){const m=modal(x.id?"Edit Result":"Add Result",formHtml([select("student_id","Student",students.map(s=>({value:s.id,label:s.full_name+" — "+s.admission_number})),x.student_id||"",true),select("subject_id","Subject",subjects.map(s=>({value:s.id,label:s.name})),x.subject_id||"",true),select("term_id","Term",terms.map(t=>({value:t.id,label:(t.name||"Term")+" — "+(t.academic_sessions?.name||"Session")})),x.term_id||"",true),input("ca_score","CA Score",x.ca_score??0,"number",true,'min="0" max="30"'),input("exam_score","Exam Score",x.exam_score??0,"number",true,'min="0" max="70"'),input("teacher_comment","Teacher Comment",x.teacher_comment||""),input("principal_comment","Principal Comment",x.principal_comment||"")],x.id?"Update Result":"Save Result"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{await adminPost({type:"result",id:x.id,...Object.fromEntries(new FormData(e.target))});m.remove();toast("Result saved.","success");adminResults(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}}}
async function adminPayments(panel){const r=await adminGet("fee_payments",{page:1,pageSize:100});panel.innerHTML='<div class="section-head"><div><p class="section-label">Payments</p><h2>Fee Payments</h2></div></div>'+table(["Student","Amount","Method","Reference","Date","Status","Actions"],(r.data||[]).map(x=>'<tr><td>'+esc(x.student_id)+'</td><td>₦'+Number(x.amount||0).toLocaleString()+'</td><td>'+esc(x.method)+'</td><td>'+esc(x.reference||"—")+'</td><td>'+new Date(x.created_at).toLocaleDateString()+'</td><td>'+pill(x.status)+'</td><td>'+(x.status==="Pending"?'<button class="btn btn-sm navy-btn payment-action" data-id="'+x.id+'" data-status="Confirmed">Confirm</button> <button class="btn btn-sm danger-btn payment-action" data-id="'+x.id+'" data-status="Rejected">Reject</button>':"—")+'</td></tr>').join(""));document.querySelectorAll(".payment-action").forEach(btn=>btn.onclick=async()=>{try{await adminPost({type:"payment-status",id:btn.dataset.id,status:btn.dataset.status});toast("Payment updated.","success");await adminPayments(panel)}catch(e){toast(e.message,"error")}});adminSectionTools(panel,"Search payments...",["Pending","Confirmed","Rejected"])}
async function adminEvents(panel){const r=await adminGet("events",{page:1,pageSize:100});panel.innerHTML='<div class="section-head"><div><p class="section-label">Events</p><h2>Manage Events</h2></div><button class="btn navy-btn" id="add-event">+ Add Event</button></div>'+table(["Date","Title","Category","Status","Actions"],r.data.map(x=>'<tr><td>'+esc(x.event_date)+'</td><td>'+esc(x.title)+'</td><td>'+esc(x.category||"Other")+'</td><td>'+pill(x.status)+'</td><td><button class="btn btn-sm btn-outline edit-event" data-id="'+x.id+'">Edit</button> <button class="btn btn-sm danger-btn delete-record" data-table="events" data-id="'+x.id+'">Delete</button></td></tr>').join(""));document.querySelector("#add-event").onclick=()=>eventModal();document.querySelectorAll(".edit-event").forEach(b=>b.onclick=()=>eventModal(r.data.find(x=>x.id===b.dataset.id)));document.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>deleteRecord("events",b.dataset.id,()=>adminEvents(panel)));adminSectionTools(panel,"Search events...",["Published","Draft","Announcement","Activity","Exam","Holiday","Other"])}
function eventModal(x={}){const m=modal(x.id?"Edit Event":"Add Event",formHtml([input("title","Title",x.title||"","text",true),'<label class="field">Description<textarea name="description" rows="4" required>'+esc(x.description||"")+'</textarea></label>',input("event_date","Date",x.event_date||"","date",true),select("category","Category",["Announcement","Activity","Exam","Holiday","Other"].map(v=>({value:v,label:v})),x.category||"Other"),input("image_url","Image URL",x.image_url||""),'<label class="field">Upload Image<input name="image_file" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label>',select("status","Status",[{value:"Published",label:"Published"},{value:"Draft",label:"Draft"}],x.status||"Published")],x.id?"Update Event":"Create Event"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),data=Object.fromEntries(fd);const file=fd.get("image_file");if(file?.size){data.image_url=(await uploadImage(file,"events")).url}delete data.image_file;await adminPost({type:"event",id:x.id,...data});m.remove();toast("Event saved.","success");adminEvents(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}}}
async function adminGallery(panel){const r=await adminGet("gallery_images",{page:1,pageSize:100});panel.innerHTML='<div class="section-head"><div><p class="section-label">Gallery</p><h2>Manage Gallery</h2></div><button class="btn navy-btn" id="add-gallery">+ Add Image</button></div><div class="gallery-admin-grid">'+r.data.map(x=>'<article class="gallery-admin-card"><img src="'+esc(x.image_url)+'" alt="'+esc(x.alt_text||x.title)+'"><div><strong>'+esc(x.title)+'</strong><p>'+esc(x.category||"Other")+'</p><button class="btn btn-sm danger-btn delete-record" data-table="gallery_images" data-id="'+x.id+'">Delete</button></div></article>').join("")+'</div>';document.querySelector("#add-gallery").onclick=()=>galleryModal();document.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>deleteRecord("gallery_images",b.dataset.id,()=>adminGallery(panel)))}
function galleryModal(){const m=modal("Add Gallery Image",formHtml([input("title","Title","","text",true),input("category","Category",""),'<label class="field">Image File<input name="image_file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" required></label>'+input("image_url","Image URL","","url",false)+input("alt_text","Alt Text","")],"Add Image"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target),data=Object.fromEntries(fd),file=fd.get("image_file");if(file?.size)data.image_url=(await uploadImage(file,"gallery")).url;if(!data.image_url)throw Error("Choose an image or provide an image URL.");delete data.image_file;await adminPost({type:"gallery",...data});m.remove();toast("Image added.","success");adminGallery(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}}}
async function adminComplaints(panel){const r=await adminGet("complaints",{page:1,pageSize:100});panel.innerHTML='<div class="section-head"><div><p class="section-label">Complaints</p><h2>Feedback & Complaints</h2></div></div>'+r.data.map(x=>'<article class="card complaint-card '+(x.status==="New"?"complaint-new":"")+'"><div class="section-head"><div><strong>'+esc(x.subject)+'</strong><p>'+esc(x.name)+' · '+esc(x.email||"No email")+'</p></div>'+pill(x.status)+'</div><div class="notice">'+esc(x.message)+'</div><div class="form-actions">'+(x.status==="New"?'<button class="btn btn-outline complaint-action" data-id="'+x.id+'" data-status="Read">Mark Read</button>':"")+(x.status!=="Resolved"?'<button class="btn navy-btn complaint-action" data-id="'+x.id+'" data-status="Resolved">Resolve</button>':"")+'</div></article>').join("")||'<p class="muted">No complaints.</p>';document.querySelectorAll(".complaint-action").forEach(b=>b.onclick=async()=>{try{await adminPost({type:"complaint-status",id:b.dataset.id,status:b.dataset.status});toast("Complaint updated.","success");adminComplaints(panel)}catch(e){toast(e.message,"error")}});adminSectionTools(panel,"Search complaints...",["New","Read","Resolved"])}
async function adminAdmissions(panel){const r=await adminGet("admission_applications",{page:1,pageSize:100});panel.innerHTML='<div class="section-head"><div><p class="section-label">Admissions</p><h2>Admission Applications</h2></div><button class="btn btn-outline" id="refresh-admissions">Refresh</button></div>'+(r.data?.length?table(["Application","Applicant","Class","Parent","Phone","Status","Submitted","Action"],r.data.map(x=>'<tr><td>'+esc(x.application_number)+'</td><td>'+esc(x.applicant_name)+'</td><td>'+esc(x.class_applied||"—")+'</td><td>'+esc(x.parent_name)+'</td><td>'+esc(x.parent_phone||"—")+'</td><td>'+pill(x.status)+'</td><td>'+new Date(x.created_at).toLocaleDateString()+'</td><td><select class="admission-status" data-id="'+x.id+'"><option value="">Change</option>'+["Pending","Under Review","Interview","Approved","Rejected"].map(s=>'<option '+(s===x.status?"selected":"")+'>'+s+'</option>').join("")+'</select></td></tr>').join("")):'<div class="notice">No admission applications yet.</div>');document.querySelector("#refresh-admissions").onclick=()=>adminAdmissions(panel);document.querySelectorAll(".admission-status").forEach(s=>s.onchange=async()=>{if(!s.value)return;try{await adminPost({type:"admission-status",id:s.dataset.id,status:s.value});toast("Admission status updated.","success");adminAdmissions(panel)}catch(e){toast(e.message,"error")}});adminSectionTools(panel,"Search admissions...",["Pending","Under Review","Interview","Approved","Rejected"])}
async function adminMessages(panel){const r=await adminGet("parent_messages",{page:1,pageSize:100});panel.innerHTML='<div class="section-head"><div><p class="section-label">Parent Communication</p><h2>Parent Messages</h2></div><button class="btn btn-outline" id="refresh-messages">Refresh</button></div>'+(r.data?.length?'<div class="message-list">'+r.data.map(x=>'<article class="dashboard-card '+(x.read_at?"":"message-unread")+'"><div class="section-head"><div><h3>'+esc(x.subject||"Parent message")+'</h3><p class="muted">From: '+esc(x.parent_profiles?.full_name||"Parent")+' · Student: '+esc(x.students?.full_name||"—")+' · '+new Date(x.created_at).toLocaleString()+'</p></div><span>'+pill(x.read_at?"Read":"Unread")+'</span></div><p>'+esc(x.body)+'</p><div class="form-actions"><button class="btn btn-sm btn-outline mark-parent-message" data-id="'+x.id+'">'+(x.read_at?"Mark Unread":"Mark Read")+'</button><button class="btn btn-sm btn-gold reply-parent-message" data-id="'+x.id+'" data-subject="'+esc(x.subject||"School message")+'">Reply</button></div></article>').join("")+'</div>':'<div class="notice">No parent messages yet.</div>');document.querySelector("#refresh-messages").onclick=()=>adminMessages(panel);document.querySelectorAll(".mark-parent-message").forEach(b=>b.onclick=async()=>{try{await adminPost({type:"message-status",id:b.dataset.id,status:b.textContent.includes("Unread")?"Read":"Unread"});adminMessages(panel)}catch(e){toast(e.message,"error")}});document.querySelectorAll(".reply-parent-message").forEach(b=>b.onclick=()=>{const m=modal("Reply to Parent",formHtml([input("subject","Subject","Re: "+b.dataset.subject),'<label class="field">Reply<textarea name="body" rows="6" required maxlength="2000"></textarea></label>'],"Send Reply"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await adminPost({type:"message-reply",id:b.dataset.id,subject:f.get("subject"),body:f.get("body")});m.remove();toast("Reply sent to parent.","success");adminMessages(panel)}catch(x){toast(x.message,"error")}}});adminSectionTools(panel,"Search parent messages...",["Unread","Read"])}
async function adminSubjects(panel){
 const r=await adminGet("subjects",{page:1,pageSize:100}),classes=(await adminGet("classes")).data||[];
 panel.innerHTML='<div class="section-head"><div><p class="section-label">Academic Setup</p><h2>Classes & Subjects</h2><p class="muted">Classes are the source of truth for student placement and teacher assignments.</p></div></div>'+
 '<div class="admin-card-grid"><section class="dashboard-card"><div class="section-head"><h3>Classes</h3><button class="btn navy-btn" id="add-class">+ Add Class</button></div>'+
 (classes.length?table(["Class","Status","Actions"],classes.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+pill(x.is_active?"Active":"Inactive")+'</td><td><button class="btn btn-sm btn-outline edit-class" data-id="'+x.id+'">Edit</button> <button class="btn btn-sm danger-btn delete-class" data-id="'+x.id+'">Delete</button></td></tr>').join("")):'<p class="muted">No classes created yet.</p>')+
 '</section><section class="dashboard-card"><div class="section-head"><h3>Subjects</h3><span class="muted">'+r.data.length+' subject(s)</span></div>'+
 '<form id="subject-form" class="inline-form"><input name="name" required placeholder="Subject name"><select name="class_id"><option value="">General / all classes</option>'+classes.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')+'</select><button class="btn navy-btn">Add Subject</button></form>'+
 '<div class="subject-list">'+r.data.map(x=>'<div class="subject-row"><span>'+esc(x.name)+(x.class_id?' — '+esc(classes.find(c=>c.id===x.class_id)?.name||"Class"):" — General")+'</span><button class="btn btn-sm danger-btn delete-record" data-table="subjects" data-id="'+x.id+'">Delete</button></div>').join("")+'</div></section></div>';
 document.querySelector("#add-class").onclick=()=>classModal();
 document.querySelectorAll(".edit-class").forEach(b=>b.onclick=()=>classModal(classes.find(x=>x.id===b.dataset.id)));
 document.querySelectorAll(".delete-class").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this class? Students, subjects or assignments linked to it may prevent deletion."))return;try{await adminPost({type:"class",action:"delete",id:b.dataset.id});toast("Class deleted.","success");adminSubjects(panel)}catch(e){toast(e.message,"error")}});
 document.querySelector("#subject-form").onsubmit=async e=>{e.preventDefault();try{await adminPost({type:"subject",...Object.fromEntries(new FormData(e.target))});toast("Subject added.","success");adminSubjects(panel)}catch(e){toast(e.message,"error")}};
 document.querySelectorAll(".delete-record").forEach(b=>b.onclick=()=>deleteRecord("subjects",b.dataset.id,()=>adminSubjects(panel)));adminSectionTools(panel,"Search subjects and classes...",[...new Set(classes.map(x=>x.name).filter(Boolean)),"General"]);
}
function classModal(x={}){const title=x.id?"Edit Class":"Add Class";const m=modal(title,formHtml([input("name","Class Name",x.name||"","text",true),select("is_active","Status",[{value:"true",label:"Active"},{value:"false",label:"Inactive"}],String(x.is_active!==false))],x.id?"Update Class":"Create Class"));m.querySelector("#modal-cancel").onclick=()=>m.remove();m.querySelector("#modal-form").onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));b.is_active=b.is_active==="true";await adminPost({type:"class",id:x.id,...b});m.remove();toast("Class saved.","success");adminSubjects(document.querySelector("#admin-panel"))}catch(e){toast(e.message,"error")}}}
async function uploadImage(file,kind){if(file.size>4*1024*1024)throw Error("Image must be 4MB or smaller.");const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});return adminPost({type:"upload-image",kind,data,mime:file.type});}
async function adminSettings(panel){const r=await api("/api/dashboard-data");panel.innerHTML='<div class="section-head"><div><p class="section-label">Settings</p><h2>Administrator Settings</h2></div></div><div class="admin-card-grid"><section class="dashboard-card"><h3>Live Overview</h3><div class="stats">'+["students","teachers","parents","results"].map(k=>'<article class="stat"><small>'+k+'</small><strong>'+Number(r.stats?.[k]||0)+'</strong></article>').join("")+'</div></section><section class="dashboard-card"><h3>Administrator Credentials</h3><p class="muted">The administrator username and password are managed securely in the Vercel environment. They are not stored in Supabase and cannot be changed from this dashboard.</p><p class="muted">After changing either credential in Vercel, redeploy the project for the new credentials to take effect.</p></section><section class="dashboard-card"><h3>Security</h3><p class="muted">Administrator access uses a signed administrator session. The session expires automatically after 12 hours.</p><button class="btn btn-outline" id="signout-settings">Logout</button></section></div>';document.querySelector("#signout-settings").onclick=()=>{localStorage.removeItem("dblossom_admin_session");location.href="/admin"};adminSectionTools(panel,"Search settings...",["Overview","Credentials","Security"])}
async function deleteRecord(table,id,refresh){if(!confirm("Delete this record? This action cannot be undone."))return;try{await adminPost({type:"delete",table,id});toast("Deleted successfully.","success");refresh()}catch(e){toast(e.message,"error")}}

if(loginForm)login();render();