'use client';

import { useMemo, useState } from "react";

type Student = { id: number; full_name?: string; admission_number?: string; class_name?: string; class_id?: number; relationship?: string };
type Invoice = { id: string; student_id: number; invoice_number: string; due_date?: string; status: string; total_amount: number; amount_paid: number; balance: number; fee_invoice_items?: Array<{ description: string; amount: number }> };
type Payment = { id: string; student_id: number; amount: number; method: string; reference?: string; status: string; paid_at?: string; created_at: string };
type Notice = { id: number; title: string; body: string; pinned?: boolean; created_at: string };
type Notification = { id: string; title: string; body: string; type: string; read_at?: string | null; created_at: string };
type Assignment = { id: string; title: string; description?: string; due_date?: string; max_score?: number; status: string; subjects?: { name?: string } | Array<{ name?: string }> };
type CalendarEvent = { id: string; title: string; description?: string; event_date: string; start_time?: string; end_time?: string };
type Message = { id: string; subject?: string; body: string; read_at?: string | null; created_at: string };
type Result = { id: number; student_id: number; ca_score?: number; exam_score?: number; total_score?: number; grade?: string; subjects?: { name?: string } | Array<{ name?: string }>; terms?: { name?: string; academic_sessions?: { name?: string } | Array<{ name?: string }> } | Array<{ name?: string; academic_sessions?: { name?: string } | Array<{ name?: string }> }> };
type Attendance = { id: number; student_id: number; date: string; status: string };

export function ParentDashboardClient({ fullName, students, announcements, invoices, payments, notifications, assignments, calendar, messages, results, attendance }: {
  fullName: string; students: Student[]; announcements: Notice[]; invoices: Invoice[]; payments: Payment[]; notifications: Notification[]; assignments: Assignment[]; calendar: CalendarEvent[]; messages: Message[]; results: Result[]; attendance: Attendance[];
}) {
  const [selectedStudent, setSelectedStudent] = useState<number | "all">("all");
  const visibleInvoices = useMemo(() => selectedStudent === "all" ? invoices : invoices.filter((item) => item.student_id === selectedStudent), [invoices, selectedStudent]);
  const visiblePayments = useMemo(() => selectedStudent === "all" ? payments : payments.filter((item) => item.student_id === selectedStudent), [payments, selectedStudent]);
  const totalBalance = visibleInvoices.reduce((sum, item) => sum + Number(item.balance || 0), 0);
  const totalPaid = visiblePayments.filter((item) => item.status === "Confirmed").reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const childName = (id: number) => students.find((item) => item.id === id)?.full_name ?? "Student";

  return <main className="min-h-screen bg-slate-50">
    <header className="bg-blue-950 px-4 py-7 text-white md:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-300">D'Blossom Model Private Schools</p><h1 className="mt-1 text-2xl font-bold">Parent Portal</h1><p className="mt-1 text-sm text-white/70">Welcome, {fullName}</p></div><a href="/auth/signout" className="rounded border border-white/20 px-4 py-2 text-sm font-semibold">Sign out</a></div></header>
    <section className="mx-auto max-w-7xl px-4 py-7 md:px-8">
      <div className="mb-6 flex flex-wrap gap-2">{students.map((student) => <button key={student.id} onClick={() => setSelectedStudent(student.id)} className={`rounded-full px-4 py-2 text-sm font-semibold ${selectedStudent === student.id ? "bg-blue-950 text-white" : "bg-white text-blue-950 ring-1 ring-slate-200"}`}>{student.full_name ?? student.admission_number}</button>)}{students.length > 1 && <button onClick={() => setSelectedStudent("all")} className={`rounded-full px-4 py-2 text-sm font-semibold ${selectedStudent === "all" ? "bg-amber-500 text-slate-950" : "bg-white text-blue-950 ring-1 ring-slate-200"}`}>All children</button>}</div>
      <div className="grid gap-4 md:grid-cols-4"><Stat title="Children linked" value={String(students.length)} /><Stat title="Fee balance" value={`₦${totalBalance.toLocaleString()}`} /><Stat title="Confirmed payments" value={`₦${totalPaid.toLocaleString()}`} /><Stat title="Notifications" value={String(notifications.filter((item) => !item.read_at).length)} /></div>
      <div className="mt-7 grid gap-6 lg:grid-cols-2">
        <Panel title="Announcements">{announcements.length ? announcements.slice(0, 8).map((item) => <article key={item.id} className="border-b border-slate-100 py-3 last:border-0"><div className="flex items-center gap-2">{item.pinned && <span className="rounded bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-800">Pinned</span>}<h3 className="font-semibold text-slate-900">{item.title}</h3></div><p className="mt-1 text-sm text-slate-600">{item.body}</p></article>) : <Empty text="No announcements yet." />}</Panel>
        <Panel title="Notifications">{notifications.length ? notifications.slice(0, 8).map((item) => <article key={item.id} className="border-b border-slate-100 py-3 last:border-0"><p className="font-semibold text-slate-900">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.body}</p></article>) : <Empty text="No notifications yet." />}</Panel>
        <Panel title="Fee invoices"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Invoice</th><th>Student</th><th>Status</th><th>Balance</th></tr></thead><tbody>{visibleInvoices.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="py-3 font-semibold">{item.invoice_number}</td><td>{childName(item.student_id)}</td><td>{item.status}</td><td>₦{Number(item.balance).toLocaleString()}</td></tr>)}{!visibleInvoices.length && <tr><td colSpan={4}><Empty text="No fee invoices yet." /></td></tr>}</tbody></table></div></Panel>
        <Panel title="Payment history"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Date</th><th>Student</th><th>Amount</th><th>Status</th></tr></thead><tbody>{visiblePayments.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="py-3">{new Date(item.created_at).toLocaleDateString()}</td><td>{childName(item.student_id)}</td><td>₦{Number(item.amount).toLocaleString()}</td><td>{item.status}</td></tr>)}{!visiblePayments.length && <tr><td colSpan={4}><Empty text="No payments yet." /></td></tr>}</tbody></table></div></Panel>
        <Panel title="Academic performance"><div className="grid gap-3">{students.map((student) => { const rows = results.filter((item) => item.student_id === student.id); const average = rows.length ? Math.round(rows.reduce((sum, item) => sum + Number(item.total_score || 0), 0) / rows.length) : 0; const attendanceRows = attendance.filter((item) => item.student_id === student.id); const present = attendanceRows.filter((item) => item.status === "present").length; const rate = attendanceRows.length ? Math.round((present / attendanceRows.length) * 100) : 0; return <article key={student.id} className="rounded-lg bg-slate-50 p-4"><p className="font-semibold">{student.full_name}</p><p className="mt-1 text-sm text-slate-500">Recorded result average: {average}% · Attendance: {rate}%</p>{rows.slice(0, 5).map((row) => <div key={row.id} className="mt-2 flex justify-between text-sm"><span>{Array.isArray(row.subjects) ? row.subjects[0]?.name : row.subjects?.name ?? "Subject"}</span><span className="font-semibold">{row.total_score ?? 0} · {row.grade ?? "—"}</span></div>)}</article>; })}{!students.length && <Empty text="No linked students yet." />}</div></Panel>
        <Panel title="Assignments">{assignments.length ? assignments.slice(0, 10).map((item) => <article key={item.id} className="border-b border-slate-100 py-3 last:border-0"><p className="font-semibold">{item.title}</p><p className="text-sm text-slate-500">{Array.isArray(item.subjects) ? item.subjects[0]?.name : item.subjects?.name ?? "Subject"} · {item.due_date ? new Date(item.due_date).toLocaleDateString() : "No deadline"}</p><p className="mt-1 text-sm text-slate-600">{item.description || "No description."}</p></article>) : <Empty text="No assignments yet." />}</Panel>
        <Panel title="School calendar">{calendar.length ? calendar.slice(0, 10).map((item) => <article key={item.id} className="border-b border-slate-100 py-3 last:border-0"><p className="font-semibold">{item.title}</p><p className="text-sm text-slate-500">{item.event_date}{item.start_time ? ` · ${item.start_time}` : ""}</p><p className="text-sm text-slate-600">{item.description || "No details."}</p></article>) : <Empty text="No calendar events yet." />}</Panel>
        <Panel title="Message inbox">{messages.length ? messages.slice(0, 10).map((item) => <article key={item.id} className="border-b border-slate-100 py-3 last:border-0"><p className="font-semibold">{item.subject || "School message"}</p><p className="mt-1 text-sm text-slate-600">{item.body}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.created_at).toLocaleString()}</p></article>) : <Empty text="No messages yet." />}</Panel>
      </div>
      <section className="mt-6 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold text-blue-950">Linked students</h2>{students.length ? <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{students.map((student) => <article key={student.id} className="rounded-lg bg-slate-50 p-4"><p className="font-semibold">{student.full_name}</p><p className="text-sm text-slate-500">{student.admission_number} · {student.class_name ?? "Class not assigned"}</p><p className="mt-1 text-xs text-slate-400">{student.relationship}</p></article>)}</div> : <Empty text="No students linked to this parent account yet." />}</section>
    </section>
  </main>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-blue-950">{title}</h2><div className="mt-3">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">{text}</p>; }
function Stat({ title, value }: { title: string; value: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-blue-950">{value}</p></article>; }
