const{admin,userFrom}=require("./_supabase");
const json=(statusCode,body)=>({statusCode,headers:{"content-type":"application/json","cache-control":"no-store"},body:JSON.stringify(body)});
exports.handler=async event=>{try{const user=await userFrom(event);if(!user)return json(401,{error:"Parent session required."});const db=admin();const{data:parent,error:pe}=await db.from("parent_profiles").select("id,full_name,email,phone,status,profile_id,address,occupation").eq("profile_id",user.id).maybeSingle();if(pe)throw pe;if(!parent||String(parent.status).toLowerCase()!=="active")return json(403,{error:"Active parent account required."});
 if(event.httpMethod==="POST"){const b=JSON.parse(event.body||"{}");if(b.type==="message"){const body=String(b.body||"").trim();if(!body)return json(400,{error:"Message is required."});const{data,error}=await db.from("parent_messages").insert({parent_id:parent.id,sender_profile_id:user.id,subject:String(b.subject||"Parent message").trim(),body,student_id:b.student_id||null}).select().single();if(error)throw error;return json(201,{data})}if(b.type==="notification-read"){const{error}=await db.from("parent_notifications").update({read_at:new Date().toISOString()}).eq("id",b.id).eq("parent_id",parent.id);if(error)throw error;return json(200,{ok:true})}return json(400,{error:"Unsupported parent action."})}
 const{data:links,error:le}=await db.from("parent_student_links").select("student_id,relationship,is_primary,students(id,full_name,admission_number,class_id,status,date_of_birth,gender,classes(name))").eq("parent_id",parent.id);if(le)throw le;
 const children=(links||[]).filter(x=>x.students).map(x=>({...x.students,relationship:x.relationship,is_primary:x.is_primary,class_name:x.students.classes?.name||null}));
 const ids=children.map(x=>x.id),classes=[...new Set(children.map(x=>x.class_id).filter(Boolean))];
 let invoices=[],payments=[],announcements=[],results=[],attendance=[],resultAccess=[],resultMatches=[];if(ids.length){let q=await db.from("result_access_grants").select("student_id,term_id,expires_at,granted_at").in("student_id",ids).order("granted_at",{ascending:false});if(q.error)throw q.error;resultAccess=q.data||[];const activeGrants=resultAccess.filter(x=>!x.expires_at||new Date(x.expires_at)>new Date());const paidPairs=activeGrants.filter(x=>x.term_id).map(x=>x.student_id+"|"+x.term_id);q=await db.from("results").select("id,student_id,term_id,subjects(name),terms(name,session_id,academic_sessions(name))").in("student_id",ids).order("created_at",{ascending:false}).limit(1000);if(q.error)throw q.error;resultMatches=q.data||[];const paidTerms=[...new Set(activeGrants.map(x=>x.term_id).filter(Boolean))];q=paidTerms.length?await db.from("results").select("id,student_id,term_id,ca_score,exam_score,total_score,grade,teacher_comment,principal_comment,subjects(name),terms(name,session_id,academic_sessions(name))").in("student_id",ids).in("term_id",paidTerms).order("created_at",{ascending:false}).limit(1000):{data:[]};if(q.error)throw q.error;results=q.data||[];q=await db.from("fee_invoices").select("id,student_id,invoice_number,due_date,status,total_amount,amount_paid,balance,created_at").in("student_id",ids).order("due_date");if(q.error)throw q.error;invoices=(q.data||[]).map(x=>({...x,student_name:children.find(s=>s.id===x.student_id)?.full_name||"Student"}));q=await db.from("fee_payments").select("id,student_id,invoice_id,amount,method,reference,status,paid_at,created_at").in("student_id",ids).order("created_at",{ascending:false}).limit(200);if(q.error)throw q.error;payments=q.data||[];q=await db.from("attendance").select("student_id,date,status").in("student_id",ids).order("date",{ascending:false}).limit(1000);if(q.error)throw q.error;attendance=q.data||[];q=await db.from("announcements").select("id,title,body,audience,target_class_id,target_student_id,pinned,status,created_at,expires_at").eq("status","Published").order("pinned",{ascending:false}).order("created_at",{ascending:false}).limit(100);if(q.error)throw q.error;announcements=(q.data||[]).filter(a=>a.audience==="all"||a.audience==="parents"||(a.target_student_id&&ids.includes(a.target_student_id))||(a.target_class_id&&classes.includes(a.target_class_id)));}  let q=await db.from("parent_notifications").select("*").eq("parent_id",parent.id).order("created_at",{ascending:false}).limit(100);if(q.error)throw q.error;const notifications=q.data||[];
 q=await db.from("parent_messages").select("*").eq("parent_id",parent.id).order("created_at",{ascending:false}).limit(100);if(q.error)throw q.error;const messages=q.data||[];
 q=await db.from("parent_calendar_events").select("*").order("event_date").limit(100);if(q.error)throw q.error;
 return json(200,{parent,children,resultAccess,resultMatches,invoices,payments,results,attendance,announcements,notifications,messages,events:q.data||[]});
}catch(e){console.error("parent-data",e);return json(500,{error:e.message||"Unable to load parent portal."})}};