const{admin,userFrom}=require("./_supabase");
const json=(statusCode,body)=>({statusCode,headers:{"content-type":"application/json","cache-control":"no-store"},body:JSON.stringify(body)});
const clean=v=>String(v??"").trim();
exports.handler=async event=>{try{
 const user=await userFrom(event);if(!user)return json(401,{error:"Teacher session required."});
 const db=admin(),{data:profile}=await db.from("profiles").select("role").eq("id",user.id).maybeSingle();
 if(profile?.role!=="teacher")return json(403,{error:"Teacher access required."});
 const{data:teacher}=await db.from("teachers").select("id,full_name,staff_id,role,assigned_class,status,profile_id").eq("profile_id",user.id).maybeSingle();
 if(!teacher||String(teacher.status).toLowerCase()!=="active"||!clean(teacher.assigned_class))return json(403,{error:"Your teacher account is not assigned to a class."});
 const{data:assign}=await db.from("teacher_assignments").select("class_id,subject_id,classes(id,name),subjects(id,name,class_id)").eq("teacher_id",teacher.id);
 const classIds=[...new Set((assign||[]).map(x=>x.class_id).filter(Boolean))];
 if(!classIds.length){const{data:cls}=await db.from("classes").select("id,name").eq("name",teacher.assigned_class).maybeSingle();if(cls)classIds.push(cls.id)}
 const students=classIds.length?(await db.from("students").select("id,admission_number,full_name,guardian_name,class_id,status,classes(name)").in("class_id",classIds).order("full_name").limit(1000)).data||[]:[];
 const studentIds=students.map(x=>x.id),subjectIds=[...new Set((assign||[]).map(x=>x.subject_id).filter(Boolean))];
 let subjects=[];if(subjectIds.length)subjects=(await db.from("subjects").select("id,name,class_id").in("id",subjectIds).order("name")).data||[];if(!subjects.length&&classIds.length)subjects=(await db.from("subjects").select("id,name,class_id").in("class_id",classIds).order("name")).data||[];
 if(event.httpMethod==="GET"){
  const[{data:terms},{data:results},{data:attendance},{data:assignments},{data:materials},{data:lessons},{data:announcements},{data:messages},{data:parentLinks},{data:school}]=await Promise.all([
   db.from("terms").select("id,name,session_id,academic_sessions(name)").order("session_id"),
   studentIds.length?db.from("results").select("id,student_id,subject_id,term_id,ca_score,exam_score,total_score,grade,teacher_comment,principal_comment,approved,recorded_by,students(full_name,admission_number),subjects(name),terms(name,academic_sessions(name))").in("student_id",studentIds).order("created_at",{ascending:false}).limit(2000):Promise.resolve({data:[]}),
   studentIds.length?db.from("attendance").select("id,student_id,date,status,recorded_by").in("student_id",studentIds).order("date",{ascending:false}).limit(1000):Promise.resolve({data:[]}),
   db.from("assignments").select("id,title,description,due_date,max_score,status,class_id,subject_id,subjects(name)").eq("teacher_id",teacher.id).order("created_at",{ascending:false}).limit(200),
   db.from("learning_materials").select("id,title,description,file_url,material_type,class_id,subject_id,subjects(name)").eq("teacher_id",teacher.id).order("created_at",{ascending:false}).limit(200),
   db.from("lesson_plans").select("id,title,objectives,content,lesson_date,class_id,subject_id,subjects(name)").eq("teacher_id",teacher.id).order("lesson_date",{ascending:false}).limit(200),
   db.from("announcements").select("id,title,body,created_at,audience,target_class_id,status").eq("posted_by",user.id).order("created_at",{ascending:false}).limit(100),
   db.from("parent_messages").select("id,subject,body,created_at,read_at,parent_id,sender_profile_id,recipient_profile_id,student_id,parent_profiles(full_name),students(full_name)").or("recipient_profile_id.eq."+user.id+",sender_profile_id.eq."+user.id).in("student_id",studentIds.length?studentIds:["00000000-0000-0000-0000-000000000000"]).order("created_at",{ascending:false}).limit(500),
   studentIds.length?db.from("parent_student_links").select("student_id,parent_id,relationship,is_primary,parent_profiles(id,full_name,profile_id,email,phone,status)").in("student_id",studentIds):Promise.resolve({data:[]}),
   db.from("school_settings").select("school_name,logo_url,address,phone").eq("id",true).maybeSingle()
  ]);
  return json(200,{teacher,classes:(assign||[]).map(x=>Array.isArray(x.classes)?x.classes[0]:x.classes).filter(Boolean),subjects,terms:terms||[],students:students.map(x=>({...x,class_name:(Array.isArray(x.classes)?x.classes[0]:x.classes)?.name})),results:(results||[]).map(x=>({...x,student_name:(Array.isArray(x.students)?x.students[0]:x.students)?.full_name,subject_name:x.subjects?.name,term:x.terms?.name,session:x.terms?.academic_sessions?.name})),attendance:attendance||[],assignments:(assignments||[]).map(x=>({...x,subject_name:x.subjects?.name})),materials:(materials||[]).map(x=>({...x,subject_name:x.subjects?.name})),lessons:(lessons||[]).map(x=>({...x,subject_name:x.subjects?.name})),announcements:announcements||[],messages:messages||[],parents:(parentLinks||[]).map(x=>({...x,parent:Array.isArray(x.parent_profiles)?x.parent_profiles[0]:x.parent_profiles})),school:school||{}});
 }
 if(event.httpMethod!=="POST")return json(405,{error:"Method Not Allowed"});
 const b=JSON.parse(event.body||"{}"),action=clean(b.action);
 if(action==="teacher-message"){const body=clean(b.body),studentId=clean(b.student_id),parentId=clean(b.parent_id);if(!body||!studentId||!parentId)return json(400,{error:"Parent, student and message are required."});if(!studentIds.includes(studentId))return json(403,{error:"Student is outside your assigned class."});const{data:link}=await db.from("parent_student_links").select("parent_id").eq("parent_id",parentId).eq("student_id",studentId).maybeSingle();if(!link)return json(403,{error:"That parent is not linked to this student."});const{data:parent}=await db.from("parent_profiles").select("profile_id").eq("id",parentId).maybeSingle();if(!parent?.profile_id)return json(404,{error:"Parent account not found."});const{data,error}=await db.from("parent_messages").insert({parent_id:parentId,sender_profile_id:user.id,recipient_profile_id:parent.profile_id,student_id:studentId,subject:clean(b.subject)||"Re: Class teacher message",body}).select().single();if(error)throw error;return json(201,{data})}
 if(action==="mark-message"){const id=clean(b.id);if(!id)return json(400,{error:"Message ID is required."});const{data:m}=await db.from("parent_messages").select("id,student_id,recipient_profile_id").eq("id",id).eq("recipient_profile_id",user.id).maybeSingle();if(!m||!studentIds.includes(m.student_id))return json(404,{error:"Message not found."});const{data,error}=await db.from("parent_messages").update({read_at:new Date().toISOString()}).eq("id",id).select().single();if(error)throw error;return json(200,{data})}
 if(action==="save-result"){
  const{data:student}=await db.from("students").select("id,class_id,classes(name)").eq("id",b.student_id).maybeSingle();if(!student||!studentIds.includes(student.id))return json(403,{error:"You can only manage results for students in your assigned class."});
  const{data:subject}=await db.from("subjects").select("id,class_id").eq("id",b.subject_id).maybeSingle();if(!subject)return json(400,{error:"Subject not found."});if(subject.class_id&&subject.class_id!==student.class_id)return json(403,{error:"That subject does not belong to the student's assigned class."});
  const{data:term}=await db.from("terms").select("id").eq("id",b.term_id).maybeSingle();if(!term)return json(400,{error:"Term not found."});
  const{data:lock}=await db.from("result_locks").select("locked").eq("class_id",student.class_id).eq("term_id",b.term_id).maybeSingle();if(lock?.locked)return json(423,{error:"Results for this class and term are locked by the administrator."});
  const ca=Number(b.ca_score),exam=Number(b.exam_score);if(!Number.isFinite(ca)||!Number.isFinite(exam)||ca<0||ca>30||exam<0||exam>70)return json(400,{error:"CA must be 0-30 and Exam must be 0-70."});
  const total=ca+exam,percentage=total,grade=percentage>=70?"A":percentage>=60?"B":percentage>=50?"C":percentage>=40?"D":"F",payload={student_id:student.id,subject_id:subject.id,term_id:term.id,ca_score:ca,exam_score:exam,total_score:total,grade,teacher_comment:clean(b.teacher_comment)||null,recorded_by:teacher.id};
  let q;if(b.id)q=await db.from("results").update(payload).eq("id",b.id).eq("student_id",student.id).select().single();else{const{data:old}=await db.from("results").select("id").eq("student_id",student.id).eq("subject_id",subject.id).eq("term_id",term.id).maybeSingle();q=old?await db.from("results").update(payload).eq("id",old.id).select().single():await db.from("results").insert(payload).select().single()}if(q.error)throw q.error;return json(200,{data:q.data});
 }
 if(action==="delete-result"){const{data:r}=await db.from("results").select("id,student_id,term_id,students(class_id)").eq("id",b.id).maybeSingle();if(!r||!studentIds.includes(r.student_id))return json(404,{error:"Result not found."});const{data:lock}=await db.from("result_locks").select("locked").eq("class_id",r.students?.class_id).eq("term_id",r.term_id).maybeSingle();if(lock?.locked)return json(423,{error:"Results are locked by the administrator."});const{error}=await db.from("results").delete().eq("id",b.id);if(error)throw error;return json(200,{ok:true})}
 if(action==="save-attendance"){if(!studentIds.includes(b.student_id))return json(403,{error:"Student is outside your assigned class."});if(!/^\d{4}-\d{2}-\d{2}$/.test(clean(b.date)))return json(400,{error:"Valid date required."});if(!["present","absent","late","excused"].includes(b.status))return json(400,{error:"Invalid attendance status."});const{data:old}=await db.from("attendance").select("id").eq("student_id",b.student_id).eq("date",b.date).maybeSingle();const q=old?await db.from("attendance").update({status:b.status,recorded_by:teacher.id}).eq("id",old.id).select().single():await db.from("attendance").insert({student_id:b.student_id,date:b.date,status:b.status,recorded_by:teacher.id}).select().single();if(q.error)throw q.error;return json(200,{data:q.data})}
 const classId=classIds[0];
 if(action==="add-subject"){const name=clean(b.name);if(!name)return json(400,{error:"Subject name is required."});const targetClass=clean(b.class_id)||classId;if(!classIds.includes(targetClass))return json(403,{error:"You can only add subjects to your assigned class."});const{data:existing}=await db.from("subjects").select("id").eq("class_id",targetClass).ilike("name",name).maybeSingle();if(existing)return json(409,{error:"That subject already exists for this class."});const q=await db.from("subjects").insert({name,class_id:targetClass}).select("id,name,class_id").single();if(q.error)throw q.error;return json(201,{data:q.data})}
 if(action==="update-subject"){const id=clean(b.id),name=clean(b.name);if(!id||!name)return json(400,{error:"Subject and name are required."});const{data:subject}=await db.from("subjects").select("id,class_id").eq("id",id).maybeSingle();if(!subject||!classIds.includes(subject.class_id))return json(403,{error:"You can only edit subjects in your assigned class."});const{data:existing}=await db.from("subjects").select("id").eq("class_id",subject.class_id).ilike("name",name).neq("id",id).maybeSingle();if(existing)return json(409,{error:"Another subject with that name already exists."});const q=await db.from("subjects").update({name}).eq("id",id).select("id,name,class_id").single();if(q.error)throw q.error;return json(200,{data:q.data})}
 if(action==="assignment"){if(!clean(b.title)||!b.subject_id)return json(400,{error:"Title and subject are required."});const q=await db.from("assignments").insert({teacher_id:teacher.id,class_id:classId,subject_id:b.subject_id,title:clean(b.title),description:clean(b.description),due_date:b.due_date||null,max_score:Number(b.max_score||100),status:"Published"}).select().single();if(q.error)throw q.error;return json(201,{data:q.data})}
 if(action==="material"){if(!clean(b.title)||!b.subject_id||!clean(b.file_url))return json(400,{error:"Title, subject and resource URL are required."});const q=await db.from("learning_materials").insert({teacher_id:teacher.id,class_id:classId,subject_id:b.subject_id,title:clean(b.title),description:clean(b.description),file_url:clean(b.file_url),material_type:clean(b.material_type)||"Resource"}).select().single();if(q.error)throw q.error;return json(201,{data:q.data})}
 if(action==="lesson"){if(!clean(b.title)||!b.subject_id||!b.lesson_date)return json(400,{error:"Title, subject and lesson date are required."});const q=await db.from("lesson_plans").insert({teacher_id:teacher.id,class_id:classId,subject_id:b.subject_id,title:clean(b.title),objectives:clean(b.objectives),content:clean(b.content),lesson_date:b.lesson_date}).select().single();if(q.error)throw q.error;return json(201,{data:q.data})}
 if(action==="announcement"){if(!clean(b.title)||!clean(b.body))return json(400,{error:"Title and message are required."});const q=await db.from("announcements").insert({title:clean(b.title),body:clean(b.body),posted_by:user.id,audience:"class",target_class_id:classId,status:"Published"}).select().single();if(q.error)throw q.error;return json(201,{data:q.data})}
 return json(400,{error:"Unsupported Teacher action."});
}catch(e){console.error(e);return json(500,{error:e.message||"Teacher operation could not be completed."})}};
