[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "/student-portal"
  to = "/pages/student-login.html"
  status = 200
  force = true

[[redirects]]
  from = "/parent-portal"
  to = "/pages/parent-login.html"
  status = 200
  force = true

[[redirects]]
  from = "/teacher-portal"
  to = "/pages/teacher-login.html"
  status = 200
  force = true

[[redirects]]
  from = "/admissions"
  to = "/pages/admissions.html"
  status = 200
  force = true

[[redirects]]
  from = "/admission-status"
  to = "/pages/admission-status.html"
  status = 200
  force = true
