import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, BookOpen, Calendar, CheckCircle, Copy, GraduationCap, Home as HomeIcon, Image, Mail, MapPin, Menu, MessageSquare, Phone, Shield, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const HERO_IMAGE = "https://media.base44.com/images/public/69c481d93678fe5f1003a517/a857fe8fa_generated_f977333f.png";
const SCHOOL_LOGO = "/manus-storage/school-logo_a34c205b.jpg";
const PROGRAMS = [
  { title: "Early Years", copy: "A gentle beginning built around curiosity, care, and confidence.", icon: HeartIcon },
  { title: "Basic Education", copy: "Strong foundations in literacy, numeracy, character, and digital learning.", icon: BookOpen },
  { title: "Senior School", copy: "Focused preparation for higher education, vocation, and purposeful leadership.", icon: GraduationCap },
];
function HeartIcon(props: { size?: number }) { return <Shield {...props} />; }

function Navbar({ open, setOpen }: { open: boolean; setOpen: (value: boolean) => void }) {
  const links = [["Home", "#home"], ["About", "#about"], ["Academics", "#academics"], ["Gallery", "#gallery"], ["Events", "#events"], ["Payment", "#payment"], ["Complaint", "#complaint"]];
  return <header className="fixed inset-x-0 top-0 z-40 border-b border-border bg-white/95 backdrop-blur-md"><div className="container flex h-16 items-center justify-between md:h-20"><a href="#home" className="flex items-center gap-3"><img src={SCHOOL_LOGO} alt="D'Blossom Model Private Schools" className="h-10 w-10 rounded-full object-cover" /><span className="font-heading text-lg font-bold text-primary">D'Blossom</span></a><nav className="hidden items-center gap-4 lg:flex"><div className="flex items-center gap-4 text-sm">{links.map(([label, href]) => <a key={label} href={href} className="text-muted-foreground hover:text-foreground">{label}</a>)}</div><Link href="/student-portal"><Button size="sm" className="bg-primary text-primary-foreground"><GraduationCap size={16} /> Student Portal</Button></Link><Link href="/admin-login"><Button size="sm" className="bg-gold text-gold-foreground hover:bg-gold/90">Admin</Button></Link></nav><button className="lg:hidden" aria-label="Open navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-border bg-white p-4 lg:hidden"><div className="grid gap-2">{links.map(([label, href]) => <a key={label} href={href} className="rounded-lg px-3 py-2 text-sm text-muted-foreground hover:bg-secondary" onClick={() => setOpen(false)}>{label}</a>)}<a href="/teacher-portal" className="rounded-lg px-3 py-2 text-sm text-accent hover:bg-accent/5" onClick={() => setOpen(false)}>Teacher Portal</a><Link href="/student-portal"><Button className="mt-2 w-full bg-primary text-primary-foreground">Student Portal</Button></Link><Link href="/admin-login"><Button className="w-full bg-gold text-gold-foreground">Admin</Button></Link></div></div>}</header>;
}

export default function Home() {
  const [open, setOpen] = useState(false);
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [complaintOpen, setComplaintOpen] = useState(false);
  const [payment, setPayment] = useState({ studentName: "", className: "JSS1", amount: "" });
  const [complaint, setComplaint] = useState({ name: "", email: "", phone: "", subject: "", message: "" });
  const { data: content } = trpc.publicContent.useQuery();
  const submitPayment = trpc.publicForms.payment.useMutation({ onSuccess: (data) => { toast.success(`Payment notification saved. Send proof via WhatsApp: +${data.whatsappNumber}`); setPaymentOpen(false); } });
  const submitComplaint = trpc.publicForms.complaint.useMutation({ onSuccess: () => { toast.success("Your message has been sent to the school office."); setComplaintOpen(false); } });
  return <div className="min-h-screen bg-background font-body text-foreground"><Navbar open={open} setOpen={setOpen} /><main className="pt-16 md:pt-20">
    <section id="home" className="relative min-h-[680px] overflow-hidden bg-primary"><div className="absolute inset-0 bg-primary/80" /><img src={HERO_IMAGE} alt="D'Blossom school community" className="absolute inset-0 h-full w-full object-cover opacity-30" /><div className="relative container grid min-h-[680px] items-center gap-10 py-16 md:grid-cols-2 md:py-24"><div className="max-w-2xl text-primary-foreground"><Badge className="mb-6 border-gold/50 bg-gold/10 text-gold">A school for becoming</Badge><h1 className="font-heading text-5xl font-bold leading-tight md:text-7xl">Where bright minds find their <span className="text-gold italic">becoming.</span></h1><p className="mt-6 max-w-xl text-lg text-primary-foreground/70">D'Blossom Model Private Schools nurtures capable, kind, and confident learners in Abeokuta, Ogun State.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#about"><Button size="lg" className="bg-gold text-gold-foreground hover:bg-gold/90">Discover our school <ArrowRight size={17} /></Button></a><Link href="/student-portal"><Button size="lg" variant="outline" className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground">Student Portal</Button></Link></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-primary-foreground/70"><span className="flex items-center gap-2"><Shield size={16} className="text-gold" /> Safe, caring community</span><span className="flex items-center gap-2"><MapPin size={16} className="text-gold" /> Abeokuta, Ogun State</span></div></div><div className="hidden justify-end md:flex"><div className="w-full max-w-md rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-5 shadow-lg backdrop-blur-sm"><img src={HERO_IMAGE} alt="D'Blossom learning environment" className="aspect-[4/3] w-full rounded-xl object-cover" /><div className="pt-5"><p className="font-heading text-3xl text-primary-foreground">Education that feels like an invitation.</p><p className="mt-3 text-sm leading-6 text-primary-foreground/70">Curiosity, discipline, and grace shape each learner's journey.</p></div></div></div></div></section>
    <section id="about" className="container grid gap-10 py-16 md:grid-cols-2 md:py-24"><div><p className="eyebrow">About D'Blossom</p><h2 className="mt-3 text-4xl font-bold text-primary md:text-5xl">A warm school with serious ambition.</h2></div><div className="space-y-5 text-muted-foreground"><p>We combine high expectations with a deep sense of belonging. Every child is known, challenged, and encouraged to grow.</p><p>Our school community is built around thoughtful teaching, strong character, and a clear pathway from JSS1 through SS3.</p><div className="grid grid-cols-3 gap-3 border-t border-border pt-6 text-center"><div><div className="font-heading text-3xl text-primary">6</div><div className="text-xs text-muted-foreground">Year groups</div></div><div><div className="font-heading text-3xl text-primary">12+</div><div className="text-xs text-muted-foreground">Years of impact</div></div><div><div className="font-heading text-3xl text-primary">100%</div><div className="text-xs text-muted-foreground">Child-centred</div></div></div></div></section>
    <section id="academics" className="bg-secondary/50 py-16 md:py-24"><div className="container"><p className="eyebrow">Academics</p><h2 className="mt-3 text-4xl font-bold text-primary md:text-5xl">Learning with a longer view.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{PROGRAMS.map(({ title, copy, icon: Icon }) => <Card key={title} className="rounded-2xl border-border bg-card shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><CardHeader><Icon size={30} className="mb-4 text-gold" /><CardTitle className="text-2xl text-primary">{title}</CardTitle></CardHeader><CardContent><p className="text-muted-foreground">{copy}</p></CardContent></Card>)}</div></div></section>
    <section id="gallery" className="container py-16 md:py-24"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Gallery</p><h2 className="mt-3 text-4xl font-bold text-primary md:text-5xl">A glimpse inside school life.</h2></div><Image className="hidden text-gold sm:block" /></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{content?.gallery?.length ? content.gallery.slice(0, 6).map((item: any) => <figure key={item.id} className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><img src={item.imageUrl} alt={item.altText || item.title} className="aspect-[4/3] w-full object-cover" /><figcaption className="p-4 text-sm text-muted-foreground">{item.title}</figcaption></figure>) : <div className="col-span-full rounded-xl border border-dashed border-border p-10 text-center text-muted-foreground">Gallery images will appear here as the school publishes them.</div>}</div></section>
    <section id="events" className="bg-secondary/50 py-16 md:py-24"><div className="container"><p className="eyebrow">Events & News</p><h2 className="mt-3 text-4xl font-bold text-primary md:text-5xl">What is happening at D'Blossom.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{content?.events?.length ? content.events.slice(0, 3).map((event: any) => <Card key={event.id} className="rounded-2xl border-border bg-card"><CardHeader><div className="flex items-center gap-2 text-sm text-gold"><Calendar size={16} /> {event.eventDate}</div><CardTitle className="text-2xl text-primary">{event.title}</CardTitle></CardHeader><CardContent><p className="text-muted-foreground">{event.description}</p></CardContent></Card>) : <div className="col-span-full rounded-xl border border-dashed border-border p-10 text-center text-muted-foreground">School events and news will appear here.</div>}</div></div></section>
    <section id="payment" className="border-y border-border bg-card py-16 md:py-24"><div className="container flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow">Payment information</p><h2 className="mt-3 text-4xl font-bold text-primary">Notify the school after payment.</h2><p className="mt-3 max-w-xl text-muted-foreground">Submit your payment details, then send your proof through WhatsApp for confirmation.</p></div><Button className="bg-accent text-accent-foreground hover:bg-accent/90" onClick={() => setPaymentOpen(true)}>I Have Paid <CheckCircle size={17} /></Button></div></section>
    <section id="complaint" className="bg-primary py-16 text-primary-foreground md:py-24"><div className="container flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow">Contact & Complaints</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">We are ready to listen.</h2><p className="mt-3 max-w-xl text-primary-foreground/70">Send a message to the school office. Your submission will be available to administrators for review.</p></div><Button className="bg-gold text-gold-foreground hover:bg-gold/90" onClick={() => setComplaintOpen(true)}>Send a message <MessageSquare size={17} /></Button></div></section>
  </main><footer className="bg-primary py-12 text-primary-foreground"><div className="container grid gap-8 md:grid-cols-4"><div><div className="flex items-center gap-3"><img src={SCHOOL_LOGO} alt="D'Blossom" className="h-10 w-10 rounded-full" /><span className="font-heading text-lg font-bold">D'Blossom</span></div><p className="mt-4 text-sm text-primary-foreground/70">Model Private Schools, Abeokuta, Ogun State.</p></div><div><h3 className="font-semibold text-gold">Quick Links</h3><div className="mt-3 grid gap-2 text-sm text-primary-foreground/70"><a href="#about">About</a><a href="#academics">Academics</a><a href="#gallery">Gallery</a><a href="#events">Events</a></div></div><div><h3 className="font-semibold text-gold">Portals</h3><div className="mt-3 grid gap-2 text-sm text-primary-foreground/70"><Link href="/student-portal">Student Portal</Link><Link href="/teacher-portal">Teacher Portal</Link><Link href="/admin-login">Admin</Link></div></div><div><h3 className="font-semibold text-gold">Contact</h3><div className="mt-3 grid gap-2 text-sm text-primary-foreground/70"><span className="flex items-center gap-2"><MapPin size={14} /> Abeokuta, Ogun State</span><span className="flex items-center gap-2"><Mail size={14} /> School office</span><span className="flex items-center gap-2"><Phone size={14} /> WhatsApp support</span></div></div></div></footer>
    {paymentOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-primary/80 p-4"><Card className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-2xl"><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-2xl text-primary">Payment notification</CardTitle><button onClick={() => setPaymentOpen(false)} aria-label="Close"><X /></button></div><p className="text-sm text-muted-foreground">After submitting, send proof via WhatsApp.</p></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (!payment.studentName.trim() || !payment.amount.trim()) return toast.error("Please complete all required fields."); submitPayment.mutate({ ...payment, amount: Number(payment.amount) }); }}><Input placeholder="Student name" value={payment.studentName} onChange={(e) => setPayment({ ...payment, studentName: e.target.value })} /><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={payment.className} onChange={(e) => setPayment({ ...payment, className: e.target.value })}>{["JSS1","JSS2","JSS3","SS1","SS2","SS3"].map((item) => <option key={item}>{item}</option>)}</select><Input type="number" placeholder="Amount in Naira" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} /><Button className="w-full bg-accent text-accent-foreground">I Have Paid <CheckCircle size={16} /></Button></form></CardContent></Card></div>}
    {complaintOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-primary/80 p-4"><Card className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl"><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-2xl text-primary">Contact the school</CardTitle><button onClick={() => setComplaintOpen(false)} aria-label="Close"><X /></button></div></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (!complaint.name.trim() || !complaint.email.trim() || !complaint.message.trim()) return toast.error("Please complete all required fields."); submitComplaint.mutate(complaint); }}><Input placeholder="Your name" value={complaint.name} onChange={(e) => setComplaint({ ...complaint, name: e.target.value })} /><Input type="email" placeholder="Email address" value={complaint.email} onChange={(e) => setComplaint({ ...complaint, email: e.target.value })} /><Input placeholder="Phone number" value={complaint.phone} onChange={(e) => setComplaint({ ...complaint, phone: e.target.value })} /><Input placeholder="Subject" value={complaint.subject} onChange={(e) => setComplaint({ ...complaint, subject: e.target.value })} /><Textarea rows={5} placeholder="Message" value={complaint.message} onChange={(e) => setComplaint({ ...complaint, message: e.target.value })} /><Button className="w-full bg-primary text-primary-foreground"><MessageSquare size={16} /> Send message</Button></form></CardContent></Card></div>}
  </div>;
}
