create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('admin', 'teacher', 'student', 'parent')),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  grade_level text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  academic_year text not null
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  student_number text not null unique,
  date_of_birth date,
  guardian_name text,
  guardian_contact text
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  class_id bigint not null references public.classes(id) on delete cascade
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  date date not null,
  status text not null check (status in ('present', 'absent', 'late', 'excused')),
  recorded_by uuid not null references public.profiles(id) on delete restrict
);

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  term text not null,
  score numeric not null check (score >= 0),
  max_score numeric not null default 100 check (max_score > 0),
  recorded_by uuid not null references public.profiles(id) on delete restrict
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  posted_by uuid not null references public.profiles(id) on delete restrict,
  class_id bigint references public.classes(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists classes_teacher_id_idx on public.classes(teacher_id);
create index if not exists students_profile_id_idx on public.students(profile_id);
create index if not exists students_class_id_idx on public.students(class_id);
create index if not exists attendance_student_date_idx on public.attendance(student_id, date);
create index if not exists grades_student_term_idx on public.grades(student_id, term);
create index if not exists announcements_class_id_idx on public.announcements(class_id);

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'admin', false);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    coalesce(new.raw_user_meta_data ->> 'role', 'student'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.subjects enable row level security;
alter table public.attendance enable row level security;
alter table public.grades enable row level security;
alter table public.announcements enable row level security;

drop policy if exists profiles_admin_all on public.profiles;
create policy profiles_admin_all on public.profiles for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select using (id = auth.uid());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists classes_admin_all on public.classes;
create policy classes_admin_all on public.classes for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists classes_teacher_read on public.classes;
create policy classes_teacher_read on public.classes for select using (teacher_id = auth.uid());
drop policy if exists classes_teacher_update on public.classes;
create policy classes_teacher_update on public.classes for update using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());

drop policy if exists students_admin_all on public.students;
create policy students_admin_all on public.students for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists students_self_read on public.students;
create policy students_self_read on public.students for select using (profile_id = auth.uid());
drop policy if exists students_teacher_read on public.students;
create policy students_teacher_read on public.students for select using (exists (select 1 from public.classes c where c.id = students.class_id and c.teacher_id = auth.uid()));

drop policy if exists subjects_admin_all on public.subjects;
create policy subjects_admin_all on public.subjects for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists subjects_teacher_read on public.subjects;
create policy subjects_teacher_read on public.subjects for select using (exists (select 1 from public.classes c where c.id = subjects.class_id and c.teacher_id = auth.uid()));

drop policy if exists attendance_admin_all on public.attendance;
create policy attendance_admin_all on public.attendance for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists attendance_teacher_class on public.attendance;
create policy attendance_teacher_class on public.attendance for all using (exists (select 1 from public.students s join public.classes c on c.id = s.class_id where s.id = attendance.student_id and c.teacher_id = auth.uid())) with check (recorded_by = auth.uid());
drop policy if exists attendance_student_read on public.attendance;
create policy attendance_student_read on public.attendance for select using (exists (select 1 from public.students s where s.id = attendance.student_id and s.profile_id = auth.uid()));

drop policy if exists grades_admin_all on public.grades;
create policy grades_admin_all on public.grades for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists grades_teacher_class on public.grades;
create policy grades_teacher_class on public.grades for all using (exists (select 1 from public.students s join public.classes c on c.id = s.class_id join public.subjects sub on sub.id = grades.subject_id and sub.class_id = c.id where s.id = grades.student_id and c.teacher_id = auth.uid())) with check (recorded_by = auth.uid());
drop policy if exists grades_student_read on public.grades;
create policy grades_student_read on public.grades for select using (exists (select 1 from public.students s where s.id = grades.student_id and s.profile_id = auth.uid()));

drop policy if exists announcements_admin_all on public.announcements;
create policy announcements_admin_all on public.announcements for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists announcements_teacher_manage on public.announcements;
create policy announcements_teacher_manage on public.announcements for all using (posted_by = auth.uid()) with check (posted_by = auth.uid());
drop policy if exists announcements_authenticated_read on public.announcements;
create policy announcements_authenticated_read on public.announcements for select using (auth.uid() is not null and (class_id is null or exists (select 1 from public.students s where s.class_id = announcements.class_id and s.profile_id = auth.uid())));
