alter table public.profiles
  add column if not exists staff_id text unique,
  add column if not exists assigned_class text,
  add column if not exists subject text,
  add column if not exists status text not null default 'Active';

alter table public.students
  add column if not exists gender text,
  add column if not exists parent_name text,
  add column if not exists parent_phone text,
  add column if not exists parent_email text,
  add column if not exists boarding_status text not null default 'Day',
  add column if not exists status text not null default 'Active';

create table if not exists public.portal_credentials (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  login_identifier text not null unique,
  login_email text not null unique,
  credential_type text not null check (credential_type in ('student', 'teacher', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  term text not null,
  session text not null,
  subjects jsonb not null default '[]'::jsonb,
  total_score numeric not null default 0,
  average numeric not null default 0,
  overall_percentage numeric not null default 0,
  teacher_comment text,
  principal_comment text,
  recorded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_name text not null,
  admission_number text,
  amount numeric not null default 0,
  payment_method text,
  reference text,
  proof_url text,
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed', 'Rejected')),
  submitted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  event_date date not null,
  image_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  title text not null,
  alt_text text,
  image_url text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'New' check (status in ('New', 'In Progress', 'Resolved')),
  created_at timestamptz not null default now()
);

create index if not exists results_student_term_session_idx on public.results(student_id, term, session);
create index if not exists payments_status_idx on public.payments(status);
create index if not exists events_date_idx on public.events(event_date);
create index if not exists complaints_status_idx on public.complaints(status);

create or replace function public.resolve_portal_login(identifier text, portal_type text)
returns table (login_email text)
language sql
stable
security definer
set search_path = public
as $$
  select pc.login_email
  from public.portal_credentials pc
  where pc.login_identifier = identifier
    and pc.credential_type = portal_type
  limit 1;
$$;

grant execute on function public.resolve_portal_login(text, text) to anon, authenticated;

alter table public.portal_credentials enable row level security;
alter table public.results enable row level security;
alter table public.payments enable row level security;
alter table public.events enable row level security;
alter table public.gallery_images enable row level security;
alter table public.complaints enable row level security;

drop policy if exists portal_credentials_admin_all on public.portal_credentials;
create policy portal_credentials_admin_all on public.portal_credentials for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists results_admin_all on public.results;
create policy results_admin_all on public.results for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists results_teacher_assigned_class on public.results;
create policy results_teacher_assigned_class on public.results for all using (
  exists (
    select 1 from public.students s join public.classes c on c.id = s.class_id
    join public.profiles p on p.id = auth.uid()
    where s.id = results.student_id and c.teacher_id = auth.uid() and p.role = 'teacher'
  )
) with check (recorded_by = auth.uid());
drop policy if exists results_student_read on public.results;
create policy results_student_read on public.results for select using (
  exists (select 1 from public.students s where s.id = results.student_id and s.profile_id = auth.uid())
);

drop policy if exists payments_admin_all on public.payments;
create policy payments_admin_all on public.payments for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists payments_public_insert on public.payments;
create policy payments_public_insert on public.payments for insert with check (auth.uid() is null or submitted_by = auth.uid());

drop policy if exists events_public_read on public.events;
create policy events_public_read on public.events for select using (true);
drop policy if exists events_admin_write on public.events;
create policy events_admin_write on public.events for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists gallery_public_read on public.gallery_images;
create policy gallery_public_read on public.gallery_images for select using (true);
drop policy if exists gallery_admin_write on public.gallery_images;
create policy gallery_admin_write on public.gallery_images for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists complaints_public_insert on public.complaints;
create policy complaints_public_insert on public.complaints for insert with check (true);
drop policy if exists complaints_admin_all on public.complaints;
create policy complaints_admin_all on public.complaints for all using (public.is_admin()) with check (public.is_admin());
