-- Keep the Supabase schema self-contained for teacher registration and portal credentials.
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  full_name text not null,
  email text,
  phone text,
  staff_id text,
  subject text,
  role text not null default 'Teaching Staff',
  assigned_class text,
  password text,
  status text not null default 'Active',
  created_at timestamptz not null default now()
);

alter table public.teachers add column if not exists profile_id uuid references public.profiles(id) on delete set null;
alter table public.teachers add column if not exists full_name text;
alter table public.teachers add column if not exists email text;
alter table public.teachers add column if not exists phone text;
alter table public.teachers add column if not exists staff_id text;
alter table public.teachers add column if not exists subject text;
alter table public.teachers add column if not exists role text default 'Teaching Staff';
alter table public.teachers add column if not exists assigned_class text;
alter table public.teachers add column if not exists password text;
alter table public.teachers add column if not exists status text default 'Active';
alter table public.teachers add column if not exists created_at timestamptz default now();

create unique index if not exists teachers_staff_id_unique_idx
  on public.teachers(staff_id)
  where staff_id is not null;
create index if not exists teachers_profile_id_idx on public.teachers(profile_id);

alter table public.teachers enable row level security;
drop policy if exists teachers_admin_all on public.teachers;
create policy teachers_admin_all on public.teachers
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists teachers_self_read on public.teachers;
create policy teachers_self_read on public.teachers
  for select using (profile_id = auth.uid());
