-- 0012_school_platform_expansion.sql
-- Non-destructive expansion for parent portal, fees, communications, learning,
-- admissions, analytics support, permissions and school operations.
-- No existing school data is deleted.

create table if not exists public.academic_sessions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.terms (
  id bigint generated by default as identity primary key,
  session_id bigint references public.academic_sessions(id) on delete cascade,
  name text not null,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  unique(session_id, name)
);

alter table public.announcements
  add column if not exists audience text not null default 'all',
  add column if not exists target_class_id bigint references public.classes(id) on delete set null,
  add column if not exists target_student_id bigint references public.students(id) on delete cascade,
  add column if not exists pinned boolean not null default false,
  add column if not exists status text not null default 'Published',
  add column if not exists publish_at timestamptz;

create index if not exists announcements_audience_idx on public.announcements(audience, status, pinned);
create index if not exists announcements_target_student_idx on public.announcements(target_student_id);

create table if not exists public.parent_notifications (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.parent_profiles(id) on delete cascade,
  title text not null,
  body text not null,
  type text not null default 'general',
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists parent_notifications_parent_idx on public.parent_notifications(parent_id, created_at desc);

create table if not exists public.parent_notification_preferences (
  parent_id uuid primary key references public.parent_profiles(id) on delete cascade,
  fee_notifications boolean not null default true,
  result_notifications boolean not null default true,
  attendance_notifications boolean not null default true,
  assignment_notifications boolean not null default true,
  event_notifications boolean not null default true,
  message_notifications boolean not null default true,
  whatsapp_notifications boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.parent_messages (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.parent_profiles(id) on delete set null,
  sender_profile_id uuid references public.profiles(id) on delete set null,
  recipient_profile_id uuid references public.profiles(id) on delete set null,
  student_id bigint references public.students(id) on delete set null,
  subject text,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists parent_messages_parent_idx on public.parent_messages(parent_id, created_at desc);
create index if not exists parent_messages_recipient_idx on public.parent_messages(recipient_profile_id, created_at desc);

create table if not exists public.parent_calendar_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  event_date date not null,
  start_time time,
  end_time time,
  audience text not null default 'all',
  class_id bigint references public.classes(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists parent_calendar_events_date_idx on public.parent_calendar_events(event_date);

create table if not exists public.fee_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  default_amount numeric(12,2) not null default 0 check (default_amount >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.fee_invoices (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  session_id bigint references public.academic_sessions(id) on delete set null,
  term_id bigint references public.terms(id) on delete set null,
  invoice_number text not null unique,
  due_date date,
  status text not null default 'Unpaid' check (status in ('Draft','Unpaid','Partially Paid','Paid','Overdue','Cancelled')),
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0),
  balance numeric(12,2) not null default 0 check (balance >= 0),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists fee_invoices_student_idx on public.fee_invoices(student_id, created_at desc);
create index if not exists fee_invoices_status_due_idx on public.fee_invoices(status, due_date);

create table if not exists public.fee_invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.fee_invoices(id) on delete cascade,
  category_id uuid references public.fee_categories(id) on delete set null,
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  created_at timestamptz not null default now()
);
create index if not exists fee_invoice_items_invoice_idx on public.fee_invoice_items(invoice_id);

create table if not exists public.fee_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.fee_invoices(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  parent_id uuid references public.parent_profiles(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  method text not null default 'Paystack',
  reference text unique,
  status text not null default 'Pending' check (status in ('Pending','Confirmed','Failed','Reversed')),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists fee_payments_invoice_idx on public.fee_payments(invoice_id, created_at desc);
create index if not exists fee_payments_student_idx on public.fee_payments(student_id, created_at desc);

create table if not exists public.fee_receipts (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.fee_payments(id) on delete cascade,
  receipt_number text not null unique,
  issued_at timestamptz not null default now()
);

create table if not exists public.student_documents (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  title text not null,
  document_type text not null default 'Other',
  file_url text not null,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists student_documents_student_idx on public.student_documents(student_id, created_at desc);

create table if not exists public.student_promotions (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete cascade,
  from_class_id bigint references public.classes(id) on delete set null,
  to_class_id bigint references public.classes(id) on delete set null,
  from_session_id bigint references public.academic_sessions(id) on delete set null,
  to_session_id bigint references public.academic_sessions(id) on delete set null,
  status text not null default 'Promoted' check (status in ('Promoted','Repeated','Pending')),
  promoted_at timestamptz not null default now(),
  promoted_by uuid references public.profiles(id) on delete set null
);
create index if not exists student_promotions_student_idx on public.student_promotions(student_id, promoted_at desc);

create table if not exists public.result_locks (
  id uuid primary key default gen_random_uuid(),
  class_id bigint references public.classes(id) on delete cascade,
  term_id bigint references public.terms(id) on delete cascade,
  locked boolean not null default true,
  locked_by uuid references public.profiles(id) on delete set null,
  locked_at timestamptz not null default now(),
  unique(class_id, term_id)
);

create table if not exists public.staff_permissions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  permission text not null,
  allowed boolean not null default true,
  unique(profile_id, permission)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_profile_id, created_at desc);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  teacher_id bigint references public.teachers(id) on delete set null,
  class_id bigint references public.classes(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  description text,
  due_date timestamptz,
  max_score numeric(8,2),
  status text not null default 'Published',
  created_at timestamptz not null default now()
);
create index if not exists assignments_class_due_idx on public.assignments(class_id, due_date);

create table if not exists public.assignment_submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  submission_text text,
  file_url text,
  score numeric(8,2),
  feedback text,
  submitted_at timestamptz,
  status text not null default 'Pending',
  unique(assignment_id, student_id)
);

create table if not exists public.learning_materials (
  id uuid primary key default gen_random_uuid(),
  teacher_id bigint references public.teachers(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  description text,
  file_url text not null,
  material_type text not null default 'Resource',
  created_at timestamptz not null default now()
);
create index if not exists learning_materials_class_idx on public.learning_materials(class_id, created_at desc);

create table if not exists public.lesson_plans (
  id uuid primary key default gen_random_uuid(),
  teacher_id bigint references public.teachers(id) on delete set null,
  class_id bigint references public.classes(id) on delete set null,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  objectives text,
  content text,
  lesson_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.admission_applications (
  id uuid primary key default gen_random_uuid(),
  application_number text not null unique,
  applicant_name text not null,
  date_of_birth date,
  gender text,
  class_applied text,
  parent_name text,
  parent_email text,
  parent_phone text,
  address text,
  status text not null default 'Pending' check (status in ('Pending','Under Review','Interview','Approved','Rejected','Converted')),
  notes text,
  interview_date timestamptz,
  interview_notes text,
  student_id bigint references public.students(id) on delete set null,
  reviewed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists admission_applications_status_idx on public.admission_applications(status, created_at desc);
create index if not exists admission_applications_search_idx on public.admission_applications(applicant_name, application_number);

create table if not exists public.admission_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.admission_applications(id) on delete cascade,
  document_type text not null,
  file_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.school_settings (
  id boolean primary key default true,
  school_name text not null default 'D''Blossom Model Private Schools',
  slogan text,
  logo_url text,
  phone text,
  email text,
  address text,
  updated_at timestamptz not null default now()
);

-- Safe defaults for the new access model.
alter table public.parent_notifications enable row level security;
alter table public.parent_notification_preferences enable row level security;
alter table public.parent_messages enable row level security;
alter table public.parent_calendar_events enable row level security;
alter table public.fee_categories enable row level security;
alter table public.fee_invoices enable row level security;
alter table public.fee_invoice_items enable row level security;
alter table public.fee_payments enable row level security;
alter table public.fee_receipts enable row level security;
alter table public.student_documents enable row level security;
alter table public.student_promotions enable row level security;
alter table public.result_locks enable row level security;
alter table public.staff_permissions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.assignments enable row level security;
alter table public.assignment_submissions enable row level security;
alter table public.learning_materials enable row level security;
alter table public.lesson_plans enable row level security;
alter table public.admission_applications enable row level security;
alter table public.admission_documents enable row level security;
alter table public.school_settings enable row level security;

drop policy if exists parent_notifications_self on public.parent_notifications;
create policy parent_notifications_self on public.parent_notifications for select to authenticated using (exists (select 1 from public.parent_profiles p where p.id = parent_notifications.parent_id and p.profile_id = auth.uid()));
drop policy if exists parent_preferences_self on public.parent_notification_preferences;
create policy parent_preferences_self on public.parent_notification_preferences for all to authenticated using (exists (select 1 from public.parent_profiles p where p.id = parent_notification_preferences.parent_id and p.profile_id = auth.uid())) with check (exists (select 1 from public.parent_profiles p where p.id = parent_notification_preferences.parent_id and p.profile_id = auth.uid()));
drop policy if exists parent_messages_self on public.parent_messages;
create policy parent_messages_self on public.parent_messages for select to authenticated using (
  exists (select 1 from public.parent_profiles p where p.id = parent_messages.parent_id and p.profile_id = auth.uid())
  or sender_profile_id = auth.uid() or recipient_profile_id = auth.uid()
);
drop policy if exists parent_calendar_public_read on public.parent_calendar_events;
create policy parent_calendar_public_read on public.parent_calendar_events for select to authenticated using (true);

create policy fee_categories_admin on public.fee_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_invoices_admin on public.fee_invoices for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_invoice_items_admin on public.fee_invoice_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_payments_admin on public.fee_payments for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fee_receipts_admin on public.fee_receipts for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy student_documents_admin on public.student_documents for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy promotions_admin on public.student_promotions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy result_locks_admin on public.result_locks for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy staff_permissions_admin on public.staff_permissions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy audit_logs_admin on public.audit_logs for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy assignments_admin on public.assignments for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy assignment_submissions_admin on public.assignment_submissions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy learning_materials_admin on public.learning_materials for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy lesson_plans_admin on public.lesson_plans for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admissions_admin on public.admission_applications for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy admission_documents_admin on public.admission_documents for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy school_settings_admin on public.school_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Parents need only the rows belonging to their linked students.
create policy fee_invoices_parent_read on public.fee_invoices for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id where l.student_id=fee_invoices.student_id and p.profile_id=auth.uid())
);
create policy fee_invoice_items_parent_read on public.fee_invoice_items for select to authenticated using (
  exists (select 1 from public.fee_invoices i join public.parent_student_links l on l.student_id=i.student_id join public.parent_profiles p on p.id=l.parent_id where i.id=fee_invoice_items.invoice_id and p.profile_id=auth.uid())
);
create policy fee_payments_parent_read on public.fee_payments for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id where l.student_id=fee_payments.student_id and p.profile_id=auth.uid())
);
create policy fee_receipts_parent_read on public.fee_receipts for select to authenticated using (
  exists (select 1 from public.fee_payments fp join public.parent_student_links l on l.student_id=fp.student_id join public.parent_profiles p on p.id=l.parent_id where fp.id=fee_receipts.payment_id and p.profile_id=auth.uid())
);
create policy student_documents_parent_read on public.student_documents for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id where l.student_id=student_documents.student_id and p.profile_id=auth.uid())
);
create policy assignments_parent_read on public.assignments for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id join public.students s on s.id=l.student_id where s.class_id=assignments.class_id and p.profile_id=auth.uid())
);
create policy learning_materials_parent_read on public.learning_materials for select to authenticated using (
  exists (select 1 from public.parent_student_links l join public.parent_profiles p on p.id=l.parent_id join public.students s on s.id=l.student_id where s.class_id=learning_materials.class_id and p.profile_id=auth.uid())
);

-- Teachers can manage classroom content for their assigned classes.
create policy assignments_teacher on public.assignments for all to authenticated using (
  exists (select 1 from public.teachers t join public.classes c on c.name=t.assigned_class where t.profile_id=auth.uid() and c.id=assignments.class_id)
) with check (
  exists (select 1 from public.teachers t join public.classes c on c.name=t.assigned_class where t.profile_id=auth.uid() and c.id=assignments.class_id)
);
create policy submissions_student on public.assignment_submissions for all to authenticated using (
  exists (select 1 from public.students s where s.id=assignment_submissions.student_id and s.profile_id=auth.uid())
) with check (
  exists (select 1 from public.students s where s.id=assignment_submissions.student_id and s.profile_id=auth.uid())
);
create policy learning_materials_teacher on public.learning_materials for all to authenticated using (
  exists (select 1 from public.teachers t where t.id=learning_materials.teacher_id and t.profile_id=auth.uid())
) with check (
  exists (select 1 from public.teachers t where t.id=learning_materials.teacher_id and t.profile_id=auth.uid())
);
create policy lesson_plans_teacher on public.lesson_plans for all to authenticated using (
  exists (select 1 from public.teachers t where t.id=lesson_plans.teacher_id and t.profile_id=auth.uid())
) with check (
  exists (select 1 from public.teachers t where t.id=lesson_plans.teacher_id and t.profile_id=auth.uid())
);

create index if not exists students_full_name_search_idx on public.students using gin (to_tsvector('simple', coalesce(full_name,'')));
create index if not exists students_admission_search_idx on public.students(admission_number);
